import { MATRIX_QA_SECONDARY_ROOM_KEY } from "./scenario-contract.js";
// QA Lab Matrix-specific fixtures run inside the shared scenario flow host.
import {
  runAllowBotsDefaultBlockScenario,
  runAllowBotsMentionsDmUnmentionedScenario,
  runAllowBotsMentionsMentionedRoomScenario,
  runAllowBotsMentionsUnmentionedOpenRoomBlockScenario,
  runAllowBotsRoomOverrideBlocksAccountTrueScenario,
  runAllowBotsRoomOverrideEnablesAccountOffScenario,
  runAllowBotsSelfSenderIgnoredScenario,
  runAllowBotsTrueUnmentionedOpenRoomScenario,
} from "./scenario-runtime-allowbots.js";
import {
  runApprovalChannelTargetBothScenario,
  runApprovalDenyReactionScenario,
  runApprovalExecMetadataChunkedScenario,
  runApprovalExecMetadataSingleEventScenario,
  runApprovalPluginMetadataSingleEventScenario,
  runApprovalThreadTargetScenario,
} from "./scenario-runtime-approval.js";
import { runDmThreadReplyOverrideScenario } from "./scenario-runtime-dm.js";
import {
  runMatrixQaE2eeCorruptCryptoIdbSnapshotScenario,
  runMatrixQaE2eeHistoryExistsBackupEmptyScenario,
  runMatrixQaE2eeServerBackupDeletedLocalReuploadRestoresScenario,
  runMatrixQaE2eeServerBackupDeletedLocalStateIntactScenario,
  runMatrixQaE2eeServerDeviceDeletedLocalStateIntactScenario,
  runMatrixQaE2eeServerDeviceDeletedReloginRecoversScenario,
  runMatrixQaE2eeStaleRecoveryKeyAfterBackupResetScenario,
  runMatrixQaE2eeStateLossExternalRecoveryKeyScenario,
  runMatrixQaE2eeStateLossNoRecoveryKeyScenario,
  runMatrixQaE2eeStateLossStoredRecoveryKeyScenario,
  runMatrixQaE2eeSyncStateLossCryptoIntactScenario,
  runMatrixQaE2eeWrongAccountRecoveryKeyScenario,
} from "./scenario-runtime-e2ee-destructive.js";
import {
  runMatrixQaE2eeArtifactRedactionScenario,
  runMatrixQaE2eeBasicReplyScenario,
  runMatrixQaE2eeBootstrapSuccessScenario,
  runMatrixQaE2eeCliAccountAddEnableE2eeScenario,
  runMatrixQaE2eeCliEncryptionSetupBootstrapFailureScenario,
  runMatrixQaE2eeCliEncryptionSetupIdempotentScenario,
  runMatrixQaE2eeCliEncryptionSetupMultiAccountScenario,
  runMatrixQaE2eeCliEncryptionSetupScenario,
  runMatrixQaE2eeCliRecoveryKeyInvalidScenario,
  runMatrixQaE2eeCliRecoveryKeySetupScenario,
  runMatrixQaE2eeCliSelfVerificationScenario,
  runMatrixQaE2eeCliSetupThenGatewayReplyScenario,
  runMatrixQaE2eeDeviceSasVerificationScenario,
  runMatrixQaE2eeDmSasVerificationScenario,
  runMatrixQaE2eeKeyBootstrapFailureScenario,
  runMatrixQaE2eeMediaImageScenario,
  runMatrixQaE2eeQrVerificationScenario,
  runMatrixQaE2eeRecoveryKeyLifecycleScenario,
  runMatrixQaE2eeRecoveryOwnerVerificationRequiredScenario,
  runMatrixQaE2eeRestartResumeScenario,
  runMatrixQaE2eeStaleDeviceHygieneScenario,
  runMatrixQaE2eeStateAfterMissingEncryptionScenario,
  runMatrixQaE2eeThreadFollowUpScenario,
  runMatrixQaE2eeVerificationNoticeNoTriggerScenario,
} from "./scenario-runtime-e2ee.js";
import {
  runInboundEditIgnoredScenario,
  runInboundEditNoDuplicateTriggerScenario,
} from "./scenario-runtime-edit.js";
import {
  runAttachmentOnlyIgnoredScenario,
  runGeneratedImageDeliveryScenario,
  runImageUnderstandingAttachmentScenario,
  runMediaTypeCoverageScenario,
  runUnsupportedMediaSafeScenario,
  runVoicePreflightMentionScenario,
} from "./scenario-runtime-media.js";
import {
  runReactionNotAReplyScenario,
  runReactionNotificationScenario,
  runReactionRedactionObservedScenario,
} from "./scenario-runtime-reaction.js";
import {
  runHomeserverRestartResumeScenario,
  runInitialCatchupThenIncrementalScenario,
  runStaleSyncReplayDedupeScenario,
} from "./scenario-runtime-restart.js";
import {
  runBlockStreamingScenario,
  runMembershipLossScenario,
  runPartialStreamingPreviewScenario,
  runQuietStreamingPreviewScenario,
  runReactionThreadedScenario,
  runRoomAutoJoinInviteScenario,
  runThreadNestedReplyShapeScenario,
  runThreadRootPreservationScenario,
  runToolProgressCommandPreviewScenario,
  runToolProgressErrorScenario,
  runToolProgressMentionSafetyScenario,
  runToolProgressPreviewOptOutScenario,
  runToolProgressPreviewScenario,
} from "./scenario-runtime-room.js";
import {
  buildExactMarkerPrompt,
  buildMatrixQaToken,
  runNoReplyExpectedScenario,
  runTopologyScopedTopLevelScenario,
  type MatrixQaScenarioContext,
} from "./scenario-runtime-shared.js";
import type { MatrixQaScenarioExecution } from "./scenario-types.js";

export async function runMxidPrefixedCommandBlockScenario(
  context: MatrixQaScenarioContext,
): Promise<MatrixQaScenarioExecution> {
  const token = buildMatrixQaToken("MATRIX_QA_MXID_COMMAND");
  return await runNoReplyExpectedScenario({
    accessToken: context.observerAccessToken,
    actorId: "observer",
    actorUserId: context.observerUserId,
    baseUrl: context.baseUrl,
    body: `${context.sutUserId} /new`,
    mentionUserIds: [context.sutUserId],
    observedEvents: context.observedEvents,
    roomId: context.roomId,
    syncState: context.syncState,
    syncStreams: context.syncStreams,
    sutUserId: context.sutUserId,
    timeoutMs: context.timeoutMs,
    token,
  });
}

export async function runMentionMetadataSpoofBlockScenario(
  context: MatrixQaScenarioContext,
): Promise<MatrixQaScenarioExecution> {
  const token = buildMatrixQaToken("MATRIX_QA_METADATA_SPOOF");
  return await runNoReplyExpectedScenario({
    accessToken: context.driverAccessToken,
    actorId: "driver",
    actorUserId: context.driverUserId,
    baseUrl: context.baseUrl,
    body: buildExactMarkerPrompt(token),
    mentionUserIds: [context.sutUserId],
    observedEvents: context.observedEvents,
    roomId: context.roomId,
    syncState: context.syncState,
    syncStreams: context.syncStreams,
    sutUserId: context.sutUserId,
    timeoutMs: context.timeoutMs,
    token,
  });
}

export async function runSecondaryRoomOpenTriggerScenario(
  context: MatrixQaScenarioContext,
): Promise<MatrixQaScenarioExecution> {
  return await runTopologyScopedTopLevelScenario({
    accessToken: context.driverAccessToken,
    actorId: "driver",
    actorUserId: context.driverUserId,
    context,
    roomKey: MATRIX_QA_SECONDARY_ROOM_KEY,
    tokenPrefix: "MATRIX_QA_SECONDARY_OPEN",
    withMention: false,
  });
}

export {
  runAllowBotsDefaultBlockScenario,
  runAllowBotsMentionsDmUnmentionedScenario,
  runAllowBotsMentionsMentionedRoomScenario,
  runAllowBotsMentionsUnmentionedOpenRoomBlockScenario,
  runAllowBotsRoomOverrideBlocksAccountTrueScenario,
  runAllowBotsRoomOverrideEnablesAccountOffScenario,
  runAllowBotsSelfSenderIgnoredScenario,
  runAllowBotsTrueUnmentionedOpenRoomScenario,
  runApprovalChannelTargetBothScenario,
  runApprovalDenyReactionScenario,
  runApprovalExecMetadataChunkedScenario,
  runApprovalExecMetadataSingleEventScenario,
  runApprovalPluginMetadataSingleEventScenario,
  runApprovalThreadTargetScenario,
  runAttachmentOnlyIgnoredScenario,
  runBlockStreamingScenario,
  runDmThreadReplyOverrideScenario,
  runGeneratedImageDeliveryScenario,
  runHomeserverRestartResumeScenario,
  runImageUnderstandingAttachmentScenario,
  runInboundEditIgnoredScenario,
  runInboundEditNoDuplicateTriggerScenario,
  runInitialCatchupThenIncrementalScenario,
  runMatrixQaE2eeArtifactRedactionScenario,
  runMatrixQaE2eeBasicReplyScenario,
  runMatrixQaE2eeBootstrapSuccessScenario,
  runMatrixQaE2eeCliAccountAddEnableE2eeScenario,
  runMatrixQaE2eeCliEncryptionSetupBootstrapFailureScenario,
  runMatrixQaE2eeCliEncryptionSetupIdempotentScenario,
  runMatrixQaE2eeCliEncryptionSetupMultiAccountScenario,
  runMatrixQaE2eeCliEncryptionSetupScenario,
  runMatrixQaE2eeCliRecoveryKeyInvalidScenario,
  runMatrixQaE2eeCliRecoveryKeySetupScenario,
  runMatrixQaE2eeCliSelfVerificationScenario,
  runMatrixQaE2eeCliSetupThenGatewayReplyScenario,
  runMatrixQaE2eeCorruptCryptoIdbSnapshotScenario,
  runMatrixQaE2eeDeviceSasVerificationScenario,
  runMatrixQaE2eeDmSasVerificationScenario,
  runMatrixQaE2eeHistoryExistsBackupEmptyScenario,
  runMatrixQaE2eeKeyBootstrapFailureScenario,
  runMatrixQaE2eeMediaImageScenario,
  runMatrixQaE2eeQrVerificationScenario,
  runMatrixQaE2eeRecoveryKeyLifecycleScenario,
  runMatrixQaE2eeRecoveryOwnerVerificationRequiredScenario,
  runMatrixQaE2eeRestartResumeScenario,
  runMatrixQaE2eeServerBackupDeletedLocalReuploadRestoresScenario,
  runMatrixQaE2eeServerBackupDeletedLocalStateIntactScenario,
  runMatrixQaE2eeServerDeviceDeletedLocalStateIntactScenario,
  runMatrixQaE2eeServerDeviceDeletedReloginRecoversScenario,
  runMatrixQaE2eeStaleDeviceHygieneScenario,
  runMatrixQaE2eeStaleRecoveryKeyAfterBackupResetScenario,
  runMatrixQaE2eeStateAfterMissingEncryptionScenario,
  runMatrixQaE2eeStateLossExternalRecoveryKeyScenario,
  runMatrixQaE2eeStateLossNoRecoveryKeyScenario,
  runMatrixQaE2eeStateLossStoredRecoveryKeyScenario,
  runMatrixQaE2eeSyncStateLossCryptoIntactScenario,
  runMatrixQaE2eeThreadFollowUpScenario,
  runMatrixQaE2eeVerificationNoticeNoTriggerScenario,
  runMatrixQaE2eeWrongAccountRecoveryKeyScenario,
  runMediaTypeCoverageScenario,
  runMembershipLossScenario,
  runPartialStreamingPreviewScenario,
  runQuietStreamingPreviewScenario,
  runReactionNotAReplyScenario,
  runReactionNotificationScenario,
  runReactionRedactionObservedScenario,
  runReactionThreadedScenario,
  runRoomAutoJoinInviteScenario,
  runStaleSyncReplayDedupeScenario,
  runThreadNestedReplyShapeScenario,
  runThreadRootPreservationScenario,
  runToolProgressCommandPreviewScenario,
  runToolProgressErrorScenario,
  runToolProgressMentionSafetyScenario,
  runToolProgressPreviewOptOutScenario,
  runToolProgressPreviewScenario,
  runUnsupportedMediaSafeScenario,
  runVoicePreflightMentionScenario,
};
