import path from "node:path";

function stripTomlComment(line: string): string {
  let quote: "'" | '"' | null = null;
  let escaping = false;
  for (let index = 0; index < line.length; index += 1) {
    const ch = line[index];
    if (escaping) {
      escaping = false;
      continue;
    }
    if (quote === '"' && ch === "\\") {
      escaping = true;
      continue;
    }
    if (quote) {
      if (ch === quote) {
        quote = null;
      }
      continue;
    }
    if (ch === "'" || ch === '"') {
      quote = ch;
      continue;
    }
    if (ch === "#") {
      return line.slice(0, index);
    }
  }
  return line;
}

function parseTomlString(value: string): string | undefined {
  const trimmed = value.trim();
  if (trimmed.startsWith('"') && trimmed.endsWith('"')) {
    try {
      return JSON.parse(trimmed) as string;
    } catch {
      return undefined;
    }
  }
  if (trimmed.startsWith("'") && trimmed.endsWith("'")) {
    return trimmed.slice(1, -1);
  }
  return undefined;
}

function parseTomlDottedKey(value: string): string[] {
  const parts: string[] = [];
  let current = "";
  let quote: "'" | '"' | null = null;
  let escaping = false;

  for (const ch of value.trim()) {
    if (escaping) {
      current += ch;
      escaping = false;
      continue;
    }
    if (quote === '"' && ch === "\\") {
      current += ch;
      escaping = true;
      continue;
    }
    if (quote) {
      current += ch;
      if (ch === quote) {
        quote = null;
      }
      continue;
    }
    if (ch === "'" || ch === '"') {
      quote = ch;
      current += ch;
      continue;
    }
    if (ch === ".") {
      parts.push(current.trim());
      current = "";
      continue;
    }
    current += ch;
  }
  if (current.trim()) {
    parts.push(current.trim());
  }
  return parts.map((part) => parseTomlString(part) ?? part);
}

function parseProjectHeader(line: string): string | undefined {
  const trimmed = line.trim();
  if (!trimmed.startsWith("[") || !trimmed.endsWith("]") || trimmed.startsWith("[[")) {
    return undefined;
  }
  const parts = parseTomlDottedKey(trimmed.slice(1, -1));
  return parts.length === 2 && parts[0] === "projects" ? parts[1] : undefined;
}

function parseTrustedInlineProjectEntries(value: string): string[] {
  const trusted: string[] = [];
  const entryPattern =
    /(?<key>"(?:\\.|[^"\\])*"|'[^']*'|[A-Za-z0-9_\-/.~:]+)\s*=\s*\{(?<body>[^{}]*(?:\{[^{}]*\}[^{}]*)*)\}/g;
  for (const match of value.matchAll(entryPattern)) {
    const key = match.groups?.key;
    const body = match.groups?.body;
    if (!key || !body || !/\btrust_level\s*=\s*["']trusted["']/.test(body)) {
      continue;
    }
    const projectPath = parseTomlString(key) ?? key.trim();
    if (projectPath) {
      trusted.push(projectPath);
    }
  }
  return trusted;
}

export function extractTrustedCodexProjectPaths(configToml: string): string[] {
  const trusted = new Set<string>();
  let currentProjectPath: string | undefined;
  let inProjectsTable = false;

  for (const rawLine of configToml.split(/\r?\n/)) {
    const line = stripTomlComment(rawLine).trim();
    if (!line) {
      continue;
    }
    if (line.startsWith("[")) {
      currentProjectPath = parseProjectHeader(line);
      inProjectsTable = line === "[projects]";
      continue;
    }

    if (currentProjectPath && /^trust_level\s*=\s*["']trusted["']\s*$/.test(line)) {
      trusted.add(currentProjectPath);
      continue;
    }

    const assignment =
      /^(?<key>"(?:\\.|[^"\\])*"|'[^']*'|[A-Za-z0-9_\-/.~:]+)\s*=\s*(?<value>.+)$/.exec(line);
    if (!assignment?.groups) {
      continue;
    }

    const key = parseTomlString(assignment.groups.key) ?? assignment.groups.key;
    const value = assignment.groups.value.trim();
    if (inProjectsTable && /^\{.*\}$/.test(value)) {
      if (/\btrust_level\s*=\s*["']trusted["']/.test(value) && key) {
        trusted.add(key);
      }
      continue;
    }
    if (key === "projects" || inProjectsTable) {
      for (const projectPath of parseTrustedInlineProjectEntries(value)) {
        trusted.add(projectPath);
      }
    }
  }

  return Array.from(trusted);
}

export function renderIsolatedCodexProjectTrustConfig(projectPaths: string[]): string {
  const normalized = Array.from(
    new Set(
      projectPaths
        .map((projectPath) => projectPath.trim())
        .filter(Boolean)
        .map((projectPath) => path.resolve(projectPath)),
    ),
  ).toSorted((left, right) => left.localeCompare(right));

  return [
    "# Generated by OpenClaw for Codex ACP sessions.",
    ...normalized.flatMap((projectPath) => [
      "",
      `[projects.${JSON.stringify(projectPath)}]`,
      'trust_level = "trusted"',
    ]),
    "",
  ].join("\n");
}
