/** Playwright-backed browser helpers loaded as one optional runtime object. */
import {
  closePageByTargetIdViaPlaywright,
  closePlaywrightBrowserConnection,
  createObservedDialogAbortSignalForPage,
  createPageViaPlaywright,
  ensurePageState,
  focusPageByTargetIdViaPlaywright,
  forceDisconnectPlaywrightForTarget,
  getObservedBrowserStateForPage,
  getObservedBrowserStateViaPlaywright,
  getPageForTargetId,
  isBrowserObservedDialogBlockedError,
  listPagesViaPlaywright,
  markObservedDialogsHandledRemotelyForPage,
  refLocator,
  respondToObservedDialogOnPage,
  retirePlaywrightBrowserConnection,
  retirePlaywrightBrowserConnectionExact,
} from "./pw-session.js";
import {
  getConsoleMessagesViaPlaywright,
  getNetworkRequestsViaPlaywright,
  getPageErrorsViaPlaywright,
} from "./pw-tools-core.activity.js";
import {
  armDialogViaPlaywright,
  armFileUploadViaPlaywright,
  downloadViaPlaywright,
  uploadViaPlaywright,
  waitForDownloadViaPlaywright,
} from "./pw-tools-core.downloads.js";
import {
  batchViaPlaywright,
  clickViaPlaywright,
  dragViaPlaywright,
  evaluateViaPlaywright,
  executeActViaPlaywright,
  fillFormViaPlaywright,
  highlightViaPlaywright,
  hoverViaPlaywright,
  pressKeyViaPlaywright,
  screenshotWithLabelsViaPlaywright,
  scrollIntoViewViaPlaywright,
  selectOptionViaPlaywright,
  setInputFilesViaPlaywright,
  takeScreenshotViaPlaywright,
  typeViaPlaywright,
  waitForViaPlaywright,
} from "./pw-tools-core.interactions.js";
import { responseBodyViaPlaywright } from "./pw-tools-core.responses.js";
import {
  closePageViaPlaywright,
  navigateViaPlaywright,
  pdfViaPlaywright,
  resizeViewportViaPlaywright,
  snapshotAiViaPlaywright,
  snapshotAriaViaPlaywright,
  snapshotRoleViaPlaywright,
  storeAriaSnapshotRefsViaPlaywright,
} from "./pw-tools-core.snapshot.js";
import {
  emulateMediaViaPlaywright,
  setDeviceViaPlaywright,
  setExtraHTTPHeadersViaPlaywright,
  setGeolocationViaPlaywright,
  setHttpCredentialsViaPlaywright,
  setLocaleViaPlaywright,
  setOfflineViaPlaywright,
  setTimezoneViaPlaywright,
} from "./pw-tools-core.state.js";
import {
  cookiesClearViaPlaywright,
  cookiesGetViaPlaywright,
  cookiesSetManyViaPlaywright,
  cookiesSetViaPlaywright,
  storageClearViaPlaywright,
  storageGetViaPlaywright,
  storageSetViaPlaywright,
} from "./pw-tools-core.storage.js";
import { traceStartViaPlaywright, traceStopViaPlaywright } from "./pw-tools-core.trace.js";

export const pwAi = {
  closePageByTargetIdViaPlaywright,
  closePlaywrightBrowserConnection,
  retirePlaywrightBrowserConnection,
  retirePlaywrightBrowserConnectionExact,
  createPageViaPlaywright,
  ensurePageState,
  forceDisconnectPlaywrightForTarget,
  focusPageByTargetIdViaPlaywright,
  createObservedDialogAbortSignalForPage,
  getObservedBrowserStateForPage,
  getObservedBrowserStateViaPlaywright,
  getPageForTargetId,
  isBrowserObservedDialogBlockedError,
  listPagesViaPlaywright,
  markObservedDialogsHandledRemotelyForPage,
  refLocator,
  respondToObservedDialogOnPage,
  armDialogViaPlaywright,
  armFileUploadViaPlaywright,
  batchViaPlaywright,
  clickViaPlaywright,
  closePageViaPlaywright,
  cookiesClearViaPlaywright,
  cookiesGetViaPlaywright,
  cookiesSetManyViaPlaywright,
  cookiesSetViaPlaywright,
  downloadViaPlaywright,
  dragViaPlaywright,
  emulateMediaViaPlaywright,
  evaluateViaPlaywright,
  executeActViaPlaywright,
  fillFormViaPlaywright,
  getConsoleMessagesViaPlaywright,
  getNetworkRequestsViaPlaywright,
  getPageErrorsViaPlaywright,
  highlightViaPlaywright,
  hoverViaPlaywright,
  navigateViaPlaywright,
  pdfViaPlaywright,
  pressKeyViaPlaywright,
  resizeViewportViaPlaywright,
  responseBodyViaPlaywright,
  scrollIntoViewViaPlaywright,
  selectOptionViaPlaywright,
  setDeviceViaPlaywright,
  setExtraHTTPHeadersViaPlaywright,
  setGeolocationViaPlaywright,
  setHttpCredentialsViaPlaywright,
  setInputFilesViaPlaywright,
  setLocaleViaPlaywright,
  setOfflineViaPlaywright,
  setTimezoneViaPlaywright,
  snapshotAiViaPlaywright,
  snapshotAriaViaPlaywright,
  snapshotRoleViaPlaywright,
  storeAriaSnapshotRefsViaPlaywright,
  screenshotWithLabelsViaPlaywright,
  storageClearViaPlaywright,
  storageGetViaPlaywright,
  storageSetViaPlaywright,
  takeScreenshotViaPlaywright,
  traceStartViaPlaywright,
  traceStopViaPlaywright,
  typeViaPlaywright,
  uploadViaPlaywright,
  waitForDownloadViaPlaywright,
  waitForViaPlaywright,
};
