export const browserCoreExamples = [
  "moltbot browser status",
  "moltbot browser start",
  "moltbot browser stop",
  "moltbot browser tabs",
  "moltbot browser open https://example.com",
  "moltbot browser focus abcd1234",
  "moltbot browser close abcd1234",
  "moltbot browser screenshot",
  "moltbot browser screenshot --full-page",
  "moltbot browser screenshot --ref 12",
  "moltbot browser snapshot",
  "moltbot browser snapshot --format aria --limit 200",
  "moltbot browser snapshot --efficient",
  "moltbot browser snapshot --labels",
];

export const browserActionExamples = [
  "moltbot browser navigate https://example.com",
  "moltbot browser resize 1280 720",
  "moltbot browser click 12 --double",
  'moltbot browser type 23 "hello" --submit',
  "moltbot browser press Enter",
  "moltbot browser hover 44",
  "moltbot browser drag 10 11",
  "moltbot browser select 9 OptionA OptionB",
  "moltbot browser upload /tmp/file.pdf",
  'moltbot browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "moltbot browser dialog --accept",
  'moltbot browser wait --text "Done"',
  "moltbot browser evaluate --fn '(el) => el.textContent' --ref 7",
  "moltbot browser console --level error",
  "moltbot browser pdf",
];
