// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActivePermissionProfileModification } from "./ActivePermissionProfileModification.js";

export type ActivePermissionProfile = {
  /**
   * Identifier from `default_permissions` or the implicit built-in default,
   * such as `:workspace` or a user-defined `[permissions.<id>]` profile.
   */
  id: string;
  /**
   * Parent profile identifier once permissions profiles support
   * inheritance. This is currently always `null`.
   */
  extends: string | null;
  /**
   * Bounded user-requested modifications applied on top of the named
   * profile, if any.
   */
  modifications: Array<ActivePermissionProfileModification>;
};
