// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AbsolutePathBuf } from "../AbsolutePathBuf.js";
import type { FileSystemSandboxEntry } from "./FileSystemSandboxEntry.js";

export type AdditionalFileSystemPermissions = {
/**
 * This will be removed in favor of `entries`.
 */
read: Array<AbsolutePathBuf> | null,
/**
 * This will be removed in favor of `entries`.
 */
write: Array<AbsolutePathBuf> | null, globScanMaxDepth?: number, entries?: Array<FileSystemSandboxEntry>, };
