// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ForcedLoginMethod } from "../ForcedLoginMethod.js";
import type { ReasoningEffort } from "../ReasoningEffort.js";
import type { ReasoningSummary } from "../ReasoningSummary.js";
import type { JsonValue } from "../serde_json/JsonValue.js";
import type { ServiceTier } from "../ServiceTier.js";
import type { Verbosity } from "../Verbosity.js";
import type { WebSearchMode } from "../WebSearchMode.js";
import type { AnalyticsConfig } from "./AnalyticsConfig.js";
import type { ApprovalsReviewer } from "./ApprovalsReviewer.js";
import type { AskForApproval } from "./AskForApproval.js";
import type { ProfileV2 } from "./ProfileV2.js";
import type { SandboxMode } from "./SandboxMode.js";
import type { SandboxWorkspaceWrite } from "./SandboxWorkspaceWrite.js";
import type { ToolsV2 } from "./ToolsV2.js";

export type Config = {
  model: string | null;
  review_model: string | null;
  model_context_window: bigint | null;
  model_auto_compact_token_limit: bigint | null;
  model_provider: string | null;
  approval_policy: AskForApproval | null /**
   * [UNSTABLE] Optional default for where approval requests are routed for
   * review.
   */;
  approvals_reviewer: ApprovalsReviewer | null;
  sandbox_mode: SandboxMode | null;
  sandbox_workspace_write: SandboxWorkspaceWrite | null;
  forced_chatgpt_workspace_id: string | null;
  forced_login_method: ForcedLoginMethod | null;
  web_search: WebSearchMode | null;
  tools: ToolsV2 | null;
  profile: string | null;
  profiles: { [key in string]?: ProfileV2 };
  instructions: string | null;
  developer_instructions: string | null;
  compact_prompt: string | null;
  model_reasoning_effort: ReasoningEffort | null;
  model_reasoning_summary: ReasoningSummary | null;
  model_verbosity: Verbosity | null;
  service_tier: ServiceTier | null;
  analytics: AnalyticsConfig | null;
} & {
  [key in string]?:
    | number
    | string
    | boolean
    | Array<JsonValue>
    | { [key in string]?: JsonValue }
    | null;
};
