// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Config } from "./Config.js";
import type { ConfigLayer } from "./ConfigLayer.js";
import type { ConfigLayerMetadata } from "./ConfigLayerMetadata.js";

export type ConfigReadResponse = {
  config: Config;
  origins: { [key in string]?: ConfigLayerMetadata };
  layers: Array<ConfigLayer> | null;
};
