// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeviceKeyProtectionPolicy } from "./DeviceKeyProtectionPolicy.js";

/**
 * Create a controller-local device key with a random key id.
 */
export type DeviceKeyCreateParams = {
/**
 * Defaults to `hardware_only` when omitted.
 */
protectionPolicy?: DeviceKeyProtectionPolicy | null, accountUserId: string, clientId: string, };
