// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeviceKeyAlgorithm } from "./DeviceKeyAlgorithm.js";

/**
 * ASN.1 DER signature returned by `device/key/sign`.
 */
export type DeviceKeySignResponse = {
  /**
   * ECDSA signature DER encoded as base64.
   */
  signatureDerBase64: string;
  /**
   * Exact bytes signed by the device key, encoded as base64. Verifiers must verify this byte
   * string directly and must not reserialize `payload`.
   */
  signedPayloadBase64: string;
  algorithm: DeviceKeyAlgorithm;
};
