// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Platform protection class for a controller-local device key.
 */
export type DeviceKeyProtectionClass =
  | "hardware_secure_enclave"
  | "hardware_tpm"
  | "os_protected_nonextractable";
