// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeviceKeySignPayload } from "./DeviceKeySignPayload.js";

/**
 * Sign an accepted structured payload with a controller-local device key.
 */
export type DeviceKeySignParams = { keyId: string; payload: DeviceKeySignPayload };
