// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Device-key algorithm reported at enrollment and signing boundaries.
 */
export type DeviceKeyAlgorithm = "ecdsa_p256_sha256";
