// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Protection policy for creating or loading a controller-local device key.
 */
export type DeviceKeyProtectionPolicy = "hardware_only" | "allow_os_protected_nonextractable";
