// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AbsolutePathBuf } from "../AbsolutePathBuf.js";
import type { HookEventName } from "./HookEventName.js";
import type { HookExecutionMode } from "./HookExecutionMode.js";
import type { HookHandlerType } from "./HookHandlerType.js";
import type { HookOutputEntry } from "./HookOutputEntry.js";
import type { HookRunStatus } from "./HookRunStatus.js";
import type { HookScope } from "./HookScope.js";
import type { HookSource } from "./HookSource.js";

export type HookRunSummary = {
  id: string;
  eventName: HookEventName;
  handlerType: HookHandlerType;
  executionMode: HookExecutionMode;
  scope: HookScope;
  sourcePath: AbsolutePathBuf;
  source: HookSource;
  displayOrder: bigint;
  status: HookRunStatus;
  statusMessage: string | null;
  startedAt: bigint;
  completedAt: bigint | null;
  durationMs: bigint | null;
  entries: Array<HookOutputEntry>;
};
