// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HookErrorInfo } from "./HookErrorInfo.js";
import type { HookMetadata } from "./HookMetadata.js";

export type HooksListEntry = {
  cwd: string;
  hooks: Array<HookMetadata>;
  warnings: Array<string>;
  errors: Array<HookErrorInfo>;
};
