// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { McpElicitationTitledSingleSelectEnumSchema } from "./McpElicitationTitledSingleSelectEnumSchema.js";
import type { McpElicitationUntitledSingleSelectEnumSchema } from "./McpElicitationUntitledSingleSelectEnumSchema.js";

export type McpElicitationSingleSelectEnumSchema =
  | McpElicitationUntitledSingleSelectEnumSchema
  | McpElicitationTitledSingleSelectEnumSchema;
