// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { McpElicitationBooleanSchema } from "./McpElicitationBooleanSchema.js";
import type { McpElicitationEnumSchema } from "./McpElicitationEnumSchema.js";
import type { McpElicitationNumberSchema } from "./McpElicitationNumberSchema.js";
import type { McpElicitationStringSchema } from "./McpElicitationStringSchema.js";

export type McpElicitationPrimitiveSchema = McpElicitationEnumSchema | McpElicitationStringSchema | McpElicitationNumberSchema | McpElicitationBooleanSchema;
