// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { McpElicitationStringFormat } from "./McpElicitationStringFormat.js";
import type { McpElicitationStringType } from "./McpElicitationStringType.js";

export type McpElicitationStringSchema = {
  type: McpElicitationStringType;
  title?: string;
  description?: string;
  minLength?: number;
  maxLength?: number;
  format?: McpElicitationStringFormat;
  default?: string;
};
