// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Resource } from "../Resource.js";
import type { ResourceTemplate } from "../ResourceTemplate.js";
import type { Tool } from "../Tool.js";
import type { McpAuthStatus } from "./McpAuthStatus.js";

export type McpServerStatus = {
  name: string;
  tools: { [key in string]?: Tool };
  resources: Array<Resource>;
  resourceTemplates: Array<ResourceTemplate>;
  authStatus: McpAuthStatus;
};
