// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommandMigration } from "./CommandMigration.js";
import type { HookMigration } from "./HookMigration.js";
import type { McpServerMigration } from "./McpServerMigration.js";
import type { PluginsMigration } from "./PluginsMigration.js";
import type { SessionMigration } from "./SessionMigration.js";
import type { SubagentMigration } from "./SubagentMigration.js";

export type MigrationDetails = {
  plugins: Array<PluginsMigration>;
  sessions: Array<SessionMigration>;
  mcpServers: Array<McpServerMigration>;
  hooks: Array<HookMigration>;
  subagents: Array<SubagentMigration>;
  commands: Array<CommandMigration>;
};
