// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InputModality } from "../InputModality.js";
import type { ReasoningEffort } from "../ReasoningEffort.js";
import type { ModelAvailabilityNux } from "./ModelAvailabilityNux.js";
import type { ModelUpgradeInfo } from "./ModelUpgradeInfo.js";
import type { ReasoningEffortOption } from "./ReasoningEffortOption.js";

export type Model = { id: string, model: string, upgrade: string | null, upgradeInfo: ModelUpgradeInfo | null, availabilityNux: ModelAvailabilityNux | null, displayName: string, description: string, hidden: boolean, supportedReasoningEfforts: Array<ReasoningEffortOption>, defaultReasoningEffort: ReasoningEffort, inputModalities: Array<InputModality>, supportsPersonality: boolean, additionalSpeedTiers: Array<string>, isDefault: boolean, };
