// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileSystemSandboxEntry } from "./FileSystemSandboxEntry.js";

export type PermissionProfileFileSystemPermissions =
  | { type: "restricted"; entries: Array<FileSystemSandboxEntry>; globScanMaxDepth?: number }
  | { type: "unrestricted" };
