// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PermissionProfileModificationParams } from "./PermissionProfileModificationParams.js";

export type PermissionProfileSelectionParams = {
  type: "profile";
  id: string;
  modifications?: Array<PermissionProfileModificationParams> | null;
};
