// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AbsolutePathBuf } from "../AbsolutePathBuf.js";
import type { RequestPermissionProfile } from "./RequestPermissionProfile.js";

export type PermissionsRequestApprovalParams = {
  threadId: string;
  turnId: string;
  itemId: string;
  cwd: AbsolutePathBuf;
  reason: string | null;
  permissions: RequestPermissionProfile;
};
