// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PluginAuthPolicy } from "./PluginAuthPolicy.js";
import type { PluginAvailability } from "./PluginAvailability.js";
import type { PluginInstallPolicy } from "./PluginInstallPolicy.js";
import type { PluginInterface } from "./PluginInterface.js";
import type { PluginSource } from "./PluginSource.js";

export type PluginSummary = {
  id: string;
  name: string;
  source: PluginSource;
  installed: boolean;
  enabled: boolean;
  installPolicy: PluginInstallPolicy;
  authPolicy: PluginAuthPolicy;
  /**
   * Availability state for installing and using the plugin.
   */
  availability: PluginAvailability;
  interface: PluginInterface | null;
};
