// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppSummary } from "./AppSummary.js";
import type { PluginAuthPolicy } from "./PluginAuthPolicy.js";

export type PluginInstallResponse = {
  authPolicy: PluginAuthPolicy;
  appsNeedingAuth: Array<AppSummary>;
};
