// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReasoningEffort } from "../ReasoningEffort.js";
import type { ReasoningSummary } from "../ReasoningSummary.js";
import type { JsonValue } from "../serde_json/JsonValue.js";
import type { ServiceTier } from "../ServiceTier.js";
import type { Verbosity } from "../Verbosity.js";
import type { WebSearchMode } from "../WebSearchMode.js";
import type { ApprovalsReviewer } from "./ApprovalsReviewer.js";
import type { AskForApproval } from "./AskForApproval.js";
import type { ToolsV2 } from "./ToolsV2.js";

export type ProfileV2 = {
  model: string | null;
  model_provider: string | null;
  approval_policy: AskForApproval | null /**
   * [UNSTABLE] Optional profile-level override for where approval requests
   * are routed for review. If omitted, the enclosing config default is
   * used.
   */;
  approvals_reviewer: ApprovalsReviewer | null;
  service_tier: ServiceTier | null;
  model_reasoning_effort: ReasoningEffort | null;
  model_reasoning_summary: ReasoningSummary | null;
  model_verbosity: Verbosity | null;
  web_search: WebSearchMode | null;
  tools: ToolsV2 | null;
  chatgpt_base_url: string | null;
} & {
  [key in string]?:
    | number
    | string
    | boolean
    | Array<JsonValue>
    | { [key in string]?: JsonValue }
    | null;
};
