// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlanType } from "../PlanType.js";
import type { CreditsSnapshot } from "./CreditsSnapshot.js";
import type { RateLimitReachedType } from "./RateLimitReachedType.js";
import type { RateLimitWindow } from "./RateLimitWindow.js";

export type RateLimitSnapshot = { limitId: string | null, limitName: string | null, primary: RateLimitWindow | null, secondary: RateLimitWindow | null, credits: CreditsSnapshot | null, planType: PlanType | null, rateLimitReachedType: RateLimitReachedType | null, };
