// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Audience for a remote-control client connection device-key proof.
 */
export type RemoteControlClientConnectionAudience = "remote_control_client_websocket";
