// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RemoteControlConnectionStatus } from "./RemoteControlConnectionStatus.js";

/**
 * Current remote-control connection status and environment id exposed to clients.
 */
export type RemoteControlStatusChangedNotification = {
  status: RemoteControlConnectionStatus;
  environmentId: string | null;
};
