// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AbsolutePathBuf } from "../AbsolutePathBuf.js";
import type { NetworkAccess } from "./NetworkAccess.js";
import type { ReadOnlyAccess } from "./ReadOnlyAccess.js";

export type SandboxPolicy =
  | { type: "dangerFullAccess" }
  | { type: "readOnly"; access: ReadOnlyAccess; networkAccess: boolean }
  | { type: "externalSandbox"; networkAccess: NetworkAccess }
  | {
      type: "workspaceWrite";
      writableRoots: Array<AbsolutePathBuf>;
      readOnlyAccess: ReadOnlyAccess;
      networkAccess: boolean;
      excludeTmpdirEnvVar: boolean;
      excludeSlashTmp: boolean;
    };
