// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AbsolutePathBuf } from "../AbsolutePathBuf.js";
import type { SkillDependencies } from "./SkillDependencies.js";
import type { SkillInterface } from "./SkillInterface.js";
import type { SkillScope } from "./SkillScope.js";

export type SkillMetadata = {
  name: string;
  description: string;
  /**
   * Legacy short_description from SKILL.md. Prefer SKILL.json interface.short_description.
   */
  shortDescription?: string;
  interface?: SkillInterface;
  dependencies?: SkillDependencies;
  path: AbsolutePathBuf;
  scope: SkillScope;
  enabled: boolean;
};
