// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SkillErrorInfo } from "./SkillErrorInfo.js";
import type { SkillMetadata } from "./SkillMetadata.js";

export type SkillsListEntry = {
  cwd: string;
  skills: Array<SkillMetadata>;
  errors: Array<SkillErrorInfo>;
};
