// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * EXPERIMENTAL - list voices supported by thread realtime.
 */
export type ThreadRealtimeListVoicesParams = Record<string, never>;
