// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Personality } from "../Personality.js";
import type { ResponseItem } from "../ResponseItem.js";
import type { JsonValue } from "../serde_json/JsonValue.js";
import type { ServiceTier } from "../ServiceTier.js";
import type { ApprovalsReviewer } from "./ApprovalsReviewer.js";
import type { AskForApproval } from "./AskForApproval.js";
import type { PermissionProfileSelectionParams } from "./PermissionProfileSelectionParams.js";
import type { SandboxMode } from "./SandboxMode.js";

/**
 * There are three ways to resume a thread:
 * 1. By thread_id: load the thread from disk by thread_id and resume it.
 * 2. By history: instantiate the thread from memory and resume it.
 * 3. By path: load the thread from disk by path and resume it.
 *
 * The precedence is: history > path > thread_id.
 * If using history or path, the thread_id param will be ignored.
 *
 * Prefer using thread_id whenever possible.
 */
export type ThreadResumeParams = {
  threadId: string;
  /**
   * [UNSTABLE] FOR CODEX CLOUD - DO NOT USE.
   * If specified, the thread will be resumed with the provided history
   * instead of loaded from disk.
   */
  history?: Array<ResponseItem> | null;
  /**
   * [UNSTABLE] Specify the rollout path to resume from.
   * If specified, the thread_id param will be ignored.
   */
  path?: string | null;
  /**
   * Configuration overrides for the resumed thread, if any.
   */
  model?: string | null;
  modelProvider?: string | null;
  serviceTier?: ServiceTier | null;
  cwd?: string | null;
  approvalPolicy?: AskForApproval | null;
  /**
   * Override where approval requests are routed for review on this thread
   * and subsequent turns.
   */
  approvalsReviewer?: ApprovalsReviewer | null;
  sandbox?: SandboxMode | null;
  /**
   * Named profile selection for the resumed thread. Cannot be combined
   * with `sandbox`. Use bounded `modifications` for supported thread
   * adjustments instead of replacing the full permissions profile.
   */
  permissions?: PermissionProfileSelectionParams | null;
  config?: { [key in string]?: JsonValue } | null;
  baseInstructions?: string | null;
  developerInstructions?: string | null;
  personality?: Personality | null;
  /**
   * When true, return only thread metadata and live-resume state without
   * populating `thread.turns`. This is useful when the client plans to call
   * `thread/turns/list` immediately after resuming.
   */
  excludeTurns?: boolean;
  /**
   * If true, persist additional EventMsg variants to the rollout file.
   * However, `thread/read`, `thread/resume`, and `thread/fork` still only
   * return the limited form of thread history for scalability reasons.
   */
  persistExtendedHistory: boolean;
};
