// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * EXPERIMENTAL - append text input to thread realtime.
 */
export type ThreadRealtimeAppendTextParams = { threadId: string; text: string };
