// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response for `thread/increment_elicitation`.
 */
export type ThreadIncrementElicitationResponse = {
  /**
   * Current out-of-band elicitation count after the increment.
   */
  count: bigint;
  /**
   * Whether timeout accounting is paused after applying the increment.
   */
  paused: boolean;
};
