// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RealtimeOutputModality } from "../RealtimeOutputModality.js";
import type { RealtimeVoice } from "../RealtimeVoice.js";
import type { ThreadRealtimeStartTransport } from "./ThreadRealtimeStartTransport.js";

/**
 * EXPERIMENTAL - start a thread-scoped realtime session.
 */
export type ThreadRealtimeStartParams = {
  threadId: string;
  /**
   * Selects text or audio output for the realtime session. Transport and voice stay
   * independent so clients can choose how they connect separately from what the model emits.
   */
  outputModality: RealtimeOutputModality;
  prompt?: string | null;
  realtimeSessionId?: string | null;
  transport?: ThreadRealtimeStartTransport | null;
  voice?: RealtimeVoice | null;
};
