// GENERATED CODE! DO NOT MODIFY BY HAND!

import type { JsonValue } from "../serde_json/JsonValue.js";
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ServiceTier } from "../ServiceTier.js";
import type { ApprovalsReviewer } from "./ApprovalsReviewer.js";
import type { AskForApproval } from "./AskForApproval.js";
import type { PermissionProfileSelectionParams } from "./PermissionProfileSelectionParams.js";
import type { SandboxMode } from "./SandboxMode.js";

/**
 * There are two ways to fork a thread:
 * 1. By thread_id: load the thread from disk by thread_id and fork it into a new thread.
 * 2. By path: load the thread from disk by path and fork it into a new thread.
 *
 * If using path, the thread_id param will be ignored.
 *
 * Prefer using thread_id whenever possible.
 */
export type ThreadForkParams = {
  threadId: string;
  /**
   * [UNSTABLE] Specify the rollout path to fork from.
   * If specified, the thread_id param will be ignored.
   */
  path?: string | null;
  /**
   * Configuration overrides for the forked thread, if any.
   */
  model?: string | null;
  modelProvider?: string | null;
  serviceTier?: ServiceTier | null;
  cwd?: string | null;
  approvalPolicy?: AskForApproval | null;
  /**
   * Override where approval requests are routed for review on this thread
   * and subsequent turns.
   */
  approvalsReviewer?: ApprovalsReviewer | null;
  sandbox?: SandboxMode | null;
  /**
   * Named profile selection for the forked thread. Cannot be combined with
   * `sandbox`. Use bounded `modifications` for supported thread
   * adjustments instead of replacing the full permissions profile.
   */
  permissions?: PermissionProfileSelectionParams | null;
  config?: { [key in string]?: JsonValue } | null;
  baseInstructions?: string | null;
  developerInstructions?: string | null;
  ephemeral?: boolean;
  /**
   * When true, return only thread metadata and live fork state without
   * populating `thread.turns`. This is useful when the client plans to call
   * `thread/turns/list` immediately after forking.
   */
  excludeTurns?: boolean;
  /**
   * If true, persist additional EventMsg variants to the rollout file.
   * However, `thread/read`, `thread/resume`, and `thread/fork` still only
   * return the limited form of thread history for scalability reasons.
   */
  persistExtendedHistory: boolean;
};
