// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AbsolutePathBuf } from "../AbsolutePathBuf.js";
import type { ReasoningEffort } from "../ReasoningEffort.js";
import type { ServiceTier } from "../ServiceTier.js";
import type { ActivePermissionProfile } from "./ActivePermissionProfile.js";
import type { ApprovalsReviewer } from "./ApprovalsReviewer.js";
import type { AskForApproval } from "./AskForApproval.js";
import type { PermissionProfile } from "./PermissionProfile.js";
import type { SandboxPolicy } from "./SandboxPolicy.js";
import type { Thread } from "./Thread.js";

export type ThreadStartResponse = {
  thread: Thread;
  model: string;
  modelProvider: string;
  serviceTier: ServiceTier | null;
  cwd: AbsolutePathBuf;
  /**
   * Instruction source files currently loaded for this thread.
   */
  instructionSources: Array<AbsolutePathBuf>;
  approvalPolicy: AskForApproval;
  /**
   * Reviewer currently used for approval requests on this thread.
   */
  approvalsReviewer: ApprovalsReviewer;
  /**
   * Legacy sandbox policy retained for compatibility. Experimental clients
   * should prefer `permissionProfile` when they need exact runtime
   * permissions.
   */
  sandbox: SandboxPolicy;
  /**
   * Full active permissions for this thread. `activePermissionProfile`
   * carries display/provenance metadata for this runtime profile.
   */
  permissionProfile: PermissionProfile | null;
  /**
   * Named or implicit built-in profile that produced the active
   * permissions, when known.
   */
  activePermissionProfile: ActivePermissionProfile | null;
  reasoningEffort: ReasoningEffort | null;
};
