// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * EXPERIMENTAL - response for appending realtime audio input.
 */
export type ThreadRealtimeAppendAudioResponse = Record<string, never>;
