// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CollaborationMode } from "../CollaborationMode.js";
import type { Personality } from "../Personality.js";
import type { ReasoningEffort } from "../ReasoningEffort.js";
import type { ReasoningSummary } from "../ReasoningSummary.js";
import type { JsonValue } from "../serde_json/JsonValue.js";
import type { ServiceTier } from "../ServiceTier.js";
import type { ApprovalsReviewer } from "./ApprovalsReviewer.js";
import type { AskForApproval } from "./AskForApproval.js";
import type { PermissionProfileSelectionParams } from "./PermissionProfileSelectionParams.js";
import type { SandboxPolicy } from "./SandboxPolicy.js";
import type { TurnEnvironmentParams } from "./TurnEnvironmentParams.js";
import type { UserInput } from "./UserInput.js";

export type TurnStartParams = {
  threadId: string;
  input: Array<UserInput>;
  /**
   * Optional turn-scoped Responses API client metadata.
   */
  responsesapiClientMetadata?: { [key in string]?: string } | null;
  /**
   * Optional turn-scoped environments.
   *
   * Omitted uses the thread sticky environments. Empty disables
   * environment access for this turn. Non-empty selects the first
   * environment as the current turn environment for this turn.
   */
  environments?: Array<TurnEnvironmentParams> | null;
  /**
   * Override the working directory for this turn and subsequent turns.
   */
  cwd?: string | null;
  /**
   * Override the approval policy for this turn and subsequent turns.
   */
  approvalPolicy?: AskForApproval | null;
  /**
   * Override where approval requests are routed for review on this turn and
   * subsequent turns.
   */
  approvalsReviewer?: ApprovalsReviewer | null;
  /**
   * Override the sandbox policy for this turn and subsequent turns.
   */
  sandboxPolicy?: SandboxPolicy | null;
  /**
   * Select a named permissions profile for this turn and subsequent turns.
   * Cannot be combined with `sandboxPolicy`. Use bounded `modifications`
   * for supported turn adjustments instead of replacing the full
   * permissions profile.
   */
  permissions?: PermissionProfileSelectionParams | null;
  /**
   * Override the model for this turn and subsequent turns.
   */
  model?: string | null;
  /**
   * Override the service tier for this turn and subsequent turns.
   */
  serviceTier?: ServiceTier | null;
  /**
   * Override the reasoning effort for this turn and subsequent turns.
   */
  effort?: ReasoningEffort | null;
  /**
   * Override the reasoning summary for this turn and subsequent turns.
   */
  summary?: ReasoningSummary | null;
  /**
   * Override the personality for this turn and subsequent turns.
   */
  personality?: Personality | null;
  /**
   * Optional JSON Schema used to constrain the final assistant message for
   * this turn.
   */
  outputSchema?: JsonValue | null;
  /**
   * EXPERIMENTAL - Set a pre-set collaboration mode.
   * Takes precedence over model, reasoning_effort, and developer instructions if set.
   *
   * For `collaboration_mode.settings.developer_instructions`, `null` means
   * "use the built-in instructions for the selected mode".
   */
  collaborationMode?: CollaborationMode | null;
};
