// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserInput } from "./UserInput.js";

export type TurnSteerParams = {
  threadId: string;
  input: Array<UserInput>;
  /**
   * Optional turn-scoped Responses API client metadata.
   */
  responsesapiClientMetadata?: { [key in string]?: string } | null;
  /**
   * Required active turn id precondition. The request fails when it does not
   * match the currently active turn.
   */
  expectedTurnId: string;
};
