// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AbsolutePathBuf } from "../AbsolutePathBuf.js";
import type { WindowsSandboxSetupMode } from "./WindowsSandboxSetupMode.js";

export type WindowsSandboxSetupStartParams = {
  mode: WindowsSandboxSetupMode;
  cwd?: AbsolutePathBuf | null;
};
