/**
 * Central public registry for canonical gateway schemas used by validators,
 * generated static types, and protocol tooling.
 */
import type { TSchema } from "typebox";
import {
  AgentEventSchema,
  AgentIdentityParamsSchema,
  AgentIdentityResultSchema,
  AgentParamsSchema,
  AgentWaitParamsSchema,
  ConversationListItemSchema,
  ConversationListParamsSchema,
  ConversationListResultSchema,
  ConversationSendParamsSchema,
  ConversationSendResultSchema,
  ConversationTurnCancelParamsSchema,
  ConversationTurnCancelResultSchema,
  ConversationTurnParamsSchema,
  ConversationTurnReplySchema,
  ConversationTurnResultSchema,
  MessageActionParamsSchema,
  PollParamsSchema,
  SendParamsSchema,
  WakeParamsSchema,
} from "./agent.js";
import {
  AuthProbeStatusSchema,
  AgentSummarySchema,
  AgentsCreateParamsSchema,
  AgentsCreateResultSchema,
  AgentsDeleteParamsSchema,
  AgentsDeleteResultSchema,
  AgentsFileEntrySchema,
  AgentsFilesGetParamsSchema,
  AgentsFilesGetResultSchema,
  AgentsFilesListParamsSchema,
  AgentsFilesListResultSchema,
  AgentsFilesSetParamsSchema,
  AgentsFilesSetResultSchema,
  AgentsListParamsSchema,
  AgentsListResultSchema,
  AgentsUpdateParamsSchema,
  AgentsUpdateResultSchema,
  ModelChoiceSchema,
  ModelsListParamsSchema,
  ModelsListResultSchema,
  ModelsProbeParamsSchema,
  ModelsProbeResultSchema,
  ModelsProbeTargetResultSchema,
  SkillsBinsParamsSchema,
  SkillsBinsResultSchema,
  SkillsDetailParamsSchema,
  SkillsDetailResultSchema,
  SkillsInstallParamsSchema,
  SkillsCuratorActionParamsSchema,
  SkillsCuratorActionResultSchema,
  SkillsCuratorStatusParamsSchema,
  SkillsCuratorStatusResultSchema,
  SkillsProposalActionParamsSchema,
  SkillsProposalApplyResultSchema,
  SkillsProposalCreateParamsSchema,
  SkillsProposalInspectParamsSchema,
  SkillsProposalInspectResultSchema,
  SkillsProposalRecordResultSchema,
  SkillsProposalRequestRevisionParamsSchema,
  SkillsProposalRequestRevisionResultSchema,
  SkillsProposalReviseParamsSchema,
  SkillsProposalUpdateParamsSchema,
  SkillsSearchParamsSchema,
  SkillsSearchResultSchema,
  SkillsSecurityVerdictsParamsSchema,
  SkillsSecurityVerdictsResultSchema,
  SkillsSkillCardParamsSchema,
  SkillsSkillCardResultSchema,
  SkillsStatusParamsSchema,
  SkillsUploadBeginParamsSchema,
  SkillsUploadChunkParamsSchema,
  SkillsUploadCommitParamsSchema,
  SkillsUpdateParamsSchema,
  ToolCatalogEntrySchema,
  ToolCatalogGroupSchema,
  ToolCatalogProfileSchema,
  ToolsCatalogParamsSchema,
  ToolsCatalogResultSchema,
  ToolsEffectiveEntrySchema,
  ToolsEffectiveGroupSchema,
  ToolsEffectiveNoticeSchema,
  ToolsEffectiveParamsSchema,
  ToolsEffectiveResultSchema,
  ToolsInvokeErrorSchema,
  ToolsInvokeParamsSchema,
  ToolsInvokeResultSchema,
} from "./agents-models-skills.js";
import {
  AgentsWorkspaceEntrySchema,
  AgentsWorkspaceFileSchema,
  AgentsWorkspaceGetParamsSchema,
  AgentsWorkspaceGetResultSchema,
  AgentsWorkspaceListParamsSchema,
  AgentsWorkspaceListResultSchema,
} from "./agents-workspace.js";
import {
  AllowedApprovalSnapshotSchema,
  ApprovalAllowDecisionSchema,
  ApprovalAllowedReasonSchema,
  ApprovalCancelledReasonSchema,
  ApprovalDecisionSchema,
  ApprovalDeniedReasonSchema,
  ApprovalExpiredReasonSchema,
  ApprovalGetParamsSchema,
  ApprovalGetResultSchema,
  ApprovalHistoryParamsSchema,
  ApprovalHistoryResultSchema,
  ApprovalKindSchema,
  ApprovalPresentationSchema,
  ApprovalResolveParamsSchema,
  ApprovalResolveResultSchema,
  SessionApprovalEventSchema,
  SessionApprovalReplaySchema,
  ApprovalSnapshotSchema,
  ApprovalTerminalReasonSchema,
  CancelledApprovalSnapshotSchema,
  DeniedApprovalSnapshotSchema,
  ExecApprovalPresentationSchema,
  ExpiredApprovalSnapshotSchema,
  PendingApprovalSnapshotSchema,
  PendingSessionApprovalEventSchema,
  PluginApprovalPresentationSchema,
  PluginApprovalSeveritySchema,
  SystemAgentApprovalPresentationSchema,
  TerminalApprovalSnapshotSchema,
  TerminalSessionApprovalEventSchema,
} from "./approvals.js";
import {
  ArtifactSummarySchema,
  ArtifactsDownloadParamsSchema,
  ArtifactsDownloadResultSchema,
  ArtifactsGetParamsSchema,
  ArtifactsGetResultSchema,
  ArtifactsListParamsSchema,
  ArtifactsListResultSchema,
} from "./artifacts.js";
import {
  AuditActivityAgentRunV1Schema,
  AuditActivityEventV1Schema,
  AuditActivityInboundMessageV1Schema,
  AuditActivityListParamsSchema,
  AuditActivityListResultSchema,
  AuditActivityOutboundMessageV1Schema,
  AuditActivityToolActionV1Schema,
} from "./audit-activity.js";
import { AuditEventSchema, AuditListParamsSchema, AuditListResultSchema } from "./audit.js";
import {
  BoardChangedEventSchema,
  BoardCommandEventSchema,
  BoardCommandSchema,
  BoardEventParamsSchema,
  BoardFocusTabCommandSchema,
  BoardGetParamsSchema,
  BoardMcpAppDescriptorSchema,
  BoardOpSchema,
  BoardSetChatDockCommandSchema,
  BoardSnapshotSchema,
  BoardTabCreateOpSchema,
  BoardTabDeleteOpSchema,
  BoardTabSchema,
  BoardTabsReorderOpSchema,
  BoardTabUpdateOpSchema,
  BoardUpdateParamsSchema,
  BoardWidgetContentSchema,
  BoardWidgetGrantParamsSchema,
  BoardWidgetHtmlContentSchema,
  BoardWidgetMcpAppContentSchema,
  BoardWidgetMoveOpSchema,
  BoardWidgetPutParamsSchema,
  BoardWidgetRemoveOpSchema,
  BoardWidgetResizeOpSchema,
  BoardWidgetSchema,
} from "./board.js";
import {
  ChannelsStartParamsSchema,
  ChannelsStopParamsSchema,
  ChannelsLogoutParamsSchema,
  TalkEventSchema,
  TalkCatalogParamsSchema,
  TalkCatalogResultSchema,
  TalkClientCreateParamsSchema,
  TalkClientCreateResultSchema,
  TalkClientCloseParamsSchema,
  TalkClientMutationResultSchema,
  TalkAgentControlResultSchema,
  TalkClientSteerParamsSchema,
  TalkClientToolCallParamsSchema,
  TalkClientToolCallResultSchema,
  TalkClientTranscriptParamsSchema,
  TalkConfigParamsSchema,
  TalkConfigResultSchema,
  TalkSessionAppendAudioParamsSchema,
  TalkSessionCancelOutputParamsSchema,
  TalkSessionCancelTurnParamsSchema,
  TalkSessionCloseParamsSchema,
  TalkSessionCreateParamsSchema,
  TalkSessionCreateResultSchema,
  TalkSessionJoinParamsSchema,
  TalkSessionJoinResultSchema,
  TalkSessionOkResultSchema,
  TalkSessionSteerParamsSchema,
  TalkSessionSubmitToolResultParamsSchema,
  TalkSessionTurnResultSchema,
  TalkSessionTurnParamsSchema,
  TalkSpeakParamsSchema,
  TalkSpeakResultSchema,
  TtsSpeakParamsSchema,
  TtsSpeakResultSchema,
  ChannelsStatusParamsSchema,
  ChannelsStatusResultSchema,
  TalkModeParamsSchema,
  WebLoginStartParamsSchema,
  WebLoginWaitParamsSchema,
} from "./channels.js";
import {
  CommandEntrySchema,
  CommandsListParamsSchema,
  CommandsListResultSchema,
} from "./commands.js";
import {
  ConfigApplyParamsSchema,
  ConfigGetParamsSchema,
  ConfigPatchParamsSchema,
  ConfigSchemaLookupParamsSchema,
  ConfigSchemaLookupResultSchema,
  ConfigSchemaParamsSchema,
  ConfigSchemaResponseSchema,
  ConfigSetParamsSchema,
  UpdateStatusParamsSchema,
  UpdateRunParamsSchema,
} from "./config.js";
import {
  CronAddParamsSchema,
  CronAddResultSchema,
  CronDeclarativeAddResultSchema,
  CronGetParamsSchema,
  CronJobSchema,
  CronListParamsSchema,
  CronRemoveParamsSchema,
  CronRunLogEntrySchema,
  CronRunParamsSchema,
  CronRunsParamsSchema,
  CronStatusParamsSchema,
  CronUpdateParamsSchema,
} from "./cron.js";
import {
  DevicePairApproveParamsSchema,
  DevicePairListParamsSchema,
  DevicePairRenameParamsSchema,
  DevicePairRemoveParamsSchema,
  DevicePairRejectParamsSchema,
  DevicePairRequestedEventSchema,
  DevicePairResolvedEventSchema,
  DevicePairSetupCodeParamsSchema,
  DevicePairSetupCodeResultSchema,
  DeviceTokenRevokeParamsSchema,
  DeviceTokenRotateParamsSchema,
} from "./devices.js";
import {
  EnvironmentSummarySchema,
  EnvironmentsCreateParamsSchema,
  EnvironmentsCreateResultSchema,
  EnvironmentsDestroyParamsSchema,
  EnvironmentsDestroyResultSchema,
  EnvironmentsListParamsSchema,
  EnvironmentsListResultSchema,
  EnvironmentsStatusParamsSchema,
  EnvironmentsStatusResultSchema,
  EnvironmentStatusSchema,
  WorkerEnvironmentMetadataSchema,
  WorkerEnvironmentStateSchema,
  WorkerTunnelStatusSchema,
} from "./environments.js";
import { GatewayErrorDetailsSchema } from "./error-codes.js";
import {
  ExecApprovalsGetParamsSchema,
  ExecApprovalsNodeGetParamsSchema,
  ExecApprovalsNodeSnapshotSchema,
  ExecApprovalsNodeSetParamsSchema,
  ExecApprovalsSetParamsSchema,
  ExecApprovalsSnapshotSchema,
  ExecApprovalGetParamsSchema,
  ExecApprovalRequestParamsSchema,
  ExecApprovalResolveParamsSchema,
} from "./exec-approvals.js";
import {
  ConnectParamsSchema,
  ErrorShapeSchema,
  EventFrameSchema,
  GatewayFrameSchema,
  HelloOkSchema,
  RequestFrameSchema,
  ResponseFrameSchema,
  ShutdownEventSchema,
  TickEventSchema,
} from "./frames.js";
import { FsDirEntrySchema, FsListDirParamsSchema, FsListDirResultSchema } from "./fs.js";
import {
  GatewaySuspendBlockerSchema,
  GatewaySuspendPrepareBusyResultSchema,
  GatewaySuspendPrepareParamsSchema,
  GatewaySuspendPrepareReadyResultSchema,
  GatewaySuspendPrepareResultSchema,
  GatewaySuspendResumeParamsSchema,
  GatewaySuspendResumeResultSchema,
  GatewaySuspendStatusReadyResultSchema,
  GatewaySuspendStatusRunningResultSchema,
  GatewaySuspendStatusParamsSchema,
  GatewaySuspendStatusResultSchema,
  GatewaySuspendTaskBlockerSchema,
} from "./gateway-suspend.js";
import { LogMigrationProtocolSchemas } from "./log-migration-protocol-schemas.js";
import {
  ChatAbortedEventSchema,
  ChatAbortParamsSchema,
  ChatDeltaEventSchema,
  ChatErrorEventSchema,
  ChatEventSchema,
  ChatFinalEventSchema,
  ChatHistoryParamsSchema,
  ChatMetadataParamsSchema,
  ChatMessageGetParamsSchema,
  ChatMessageGetResultSchema,
  ChatInjectParamsSchema,
  ChatSendParamsSchema,
  ChatToolTitlesParamsSchema,
  ChatToolTitlesResultSchema,
} from "./logs-chat.js";
import {
  NodeDescribeParamsSchema,
  NodeEventParamsSchema,
  NodeEventResultSchema,
  NodePendingDrainParamsSchema,
  NodePendingDrainResultSchema,
  NodePendingEnqueueParamsSchema,
  NodePendingEnqueueResultSchema,
  NodePresenceAlivePayloadSchema,
  NodeListParamsSchema,
  NodePendingAckParamsSchema,
  NodePairApproveParamsSchema,
  NodePairListParamsSchema,
  NodePairRemoveParamsSchema,
  NodePairRejectParamsSchema,
  NodePluginToolDescriptorSchema,
  NodePluginToolsUpdateParamsSchema,
  NodeSkillDescriptorSchema,
  NodeSkillsUpdateParamsSchema,
  NodeRenameParamsSchema,
} from "./nodes.js";
import {
  SystemChangeEntrySchema,
  SystemChangeKindSchema,
  SystemChangeSourceSchema,
  SystemChangesListParamsSchema,
  SystemChangesListResultSchema,
  SystemAgentChatHistoryParamsSchema,
  SystemAgentChatHistoryResultSchema,
  SystemAgentChatHistoryTurnSchema,
  SystemAgentChatParamsSchema,
  SystemAgentChatResultSchema,
  SystemAgentSetupActivateParamsSchema,
  SystemAgentSetupActivateResultSchema,
  SystemAgentSetupAuthStartParamsSchema,
  SystemAgentSetupAuthStartResultSchema,
  SystemAgentSetupDetectParamsSchema,
  SystemAgentSetupDetectResultSchema,
  SystemAgentSetupVerifyParamsSchema,
  SystemAgentSetupVerifyResultSchema,
} from "./openclaw.js";
import {
  PluginApprovalRequestParamsSchema,
  PluginApprovalResolveParamsSchema,
} from "./plugin-approvals.js";
import {
  PluginCatalogClawHubInstallSchema,
  PluginCatalogEntrySchema,
  PluginCatalogInstallActionSchema,
  PluginCatalogOfficialInstallSchema,
  PluginControlUiDescriptorSchema,
  PluginSearchPackageSchema,
  PluginSearchResultEntrySchema,
  PluginsInstallParamsSchema,
  PluginsInstallResultSchema,
  PluginsListParamsSchema,
  PluginsListResultSchema,
  PluginsRefreshParamsSchema,
  PluginsRefreshResultSchema,
  PluginsSearchParamsSchema,
  PluginsSearchResultSchema,
  PluginsSessionActionFailureResultSchema,
  PluginsSessionActionParamsSchema,
  PluginsSessionActionResultSchema,
  PluginsSessionActionSuccessResultSchema,
  PluginsSetEnabledParamsSchema,
  PluginsSetEnabledResultSchema,
  PluginsUiDescriptorsParamsSchema,
  PluginsUiDescriptorsResultSchema,
  PluginsUninstallParamsSchema,
  PluginsUninstallResultSchema,
} from "./plugins.js";
import { NodeInvokeProtocolSchemas } from "./protocol-schemas-node-invoke.js";
import { NodePresenceProtocolSchemas } from "./protocol-schemas-node-presence.js";
import { PushTestParamsSchema, PushTestResultSchema } from "./push.js";
import {
  QuestionAnswersSchema,
  QuestionGetParamsSchema,
  QuestionGetResultSchema,
  QuestionListParamsSchema,
  QuestionListResultSchema,
  QuestionOptionSchema,
  QuestionRecordSchema,
  QuestionRequestParamsSchema,
  QuestionRequestQuestionSchema,
  QuestionRequestResultSchema,
  QuestionResolvedEventSchema,
  QuestionResolveParamsSchema,
  QuestionResolveResultSchema,
  QuestionSchema,
  QuestionStatusSchema,
  QuestionWaitAnswerParamsSchema,
  QuestionWaitAnswerResultSchema,
} from "./questions.js";
import {
  SecretsReloadParamsSchema,
  SecretsResolveAssignmentSchema,
  SecretsResolveParamsSchema,
  SecretsResolveResultSchema,
} from "./secrets.js";
import { SessionPlacementProtocolSchemas } from "./session-placement.js";
import {
  SessionCatalogCapabilitiesSchema,
  SessionCatalogDescriptorSchema,
  SessionCatalogHostSchema,
  SessionCatalogSchema,
  SessionCatalogSessionSchema,
  SessionCatalogTranscriptItemSchema,
  SessionsCatalogArchiveParamsSchema,
  SessionsCatalogArchiveResultSchema,
  SessionsCatalogContinueParamsSchema,
  SessionsCatalogContinueResultSchema,
  SessionsCatalogListParamsSchema,
  SessionsCatalogListResultSchema,
  SessionsCatalogReadParamsSchema,
  SessionsCatalogReadResultSchema,
} from "./sessions-catalog.js";
import {
  SessionsAbortParamsSchema,
  SessionsCompactParamsSchema,
  SessionsCompactionBranchParamsSchema,
  SessionsCompactionBranchResultSchema,
  SessionsCompactionGetParamsSchema,
  SessionsCompactionGetResultSchema,
  SessionsCompactionListParamsSchema,
  SessionsCompactionListResultSchema,
  SessionsCompactionRestoreParamsSchema,
  SessionsCompactionRestoreResultSchema,
  SessionsForkParamsSchema,
  SessionsForkResultSchema,
  SessionsRewindParamsSchema,
  SessionsRewindResultSchema,
  SessionFileBrowserEntrySchema,
  SessionFileBrowserResultSchema,
  SessionCompactionCheckpointSchema,
  SessionFileEntrySchema,
  SessionFileKindSchema,
  SessionFileRelevanceSchema,
  SessionOperationEventSchema,
  SessionWorktreeInfoSchema,
  SessionsCleanupParamsSchema,
  SessionsCreateParamsSchema,
  SessionsCreateResultSchema,
  SessionsDeleteParamsSchema,
  SessionsDescribeParamsSchema,
  SessionGroupSchema,
  SessionsGroupsDeleteParamsSchema,
  SessionsGroupsListParamsSchema,
  SessionsGroupsListResultSchema,
  SessionsGroupsMutationResultSchema,
  SessionsGroupsPutParamsSchema,
  SessionsGroupsRenameParamsSchema,
  SessionDiffFileSchema,
  SessionDiffFileStatusSchema,
  SessionsDiffParamsSchema,
  SessionsDiffResultSchema,
  SessionsFilesGetParamsSchema,
  SessionsFilesGetResultSchema,
  SessionsFilesListParamsSchema,
  SessionsFilesListResultSchema,
  SessionsFilesRevealParamsSchema,
  SessionsFilesRevealResultSchema,
  SessionsFilesSetParamsSchema,
  SessionsFilesSetResultSchema,
  SessionsListParamsSchema,
  SessionsMessagesSubscribeParamsSchema,
  SessionsMessagesUnsubscribeParamsSchema,
  SessionsPatchParamsSchema,
  SessionsPluginPatchParamsSchema,
  SessionsPluginPatchResultSchema,
  SessionsPreviewParamsSchema,
  SessionsResetParamsSchema,
  SessionsResolveParamsSchema,
  SessionsSearchHitSchema,
  SessionsSearchParamsSchema,
  SessionsSearchResultSchema,
  SessionsSendParamsSchema,
  SessionsUsageParamsSchema,
} from "./sessions.js";
import { SkillWorkshopProtocolSchemas } from "./skill-protocol-schemas.js";
import { PresenceEntrySchema, SnapshotSchema, StateVersionSchema } from "./snapshot.js";
import { SystemInfoParamsSchema, SystemInfoResultSchema } from "./system-info.js";
import { TalkSessionAcknowledgeMarkParamsSchema } from "./talk-marks.js";
import {
  TaskSuggestionEventSchema,
  TaskSuggestionResolutionSchema,
  TaskSuggestionSchema,
  TaskSuggestionsAcceptParamsSchema,
  TaskSuggestionsAcceptResultSchema,
  TaskSuggestionsCreateParamsSchema,
  TaskSuggestionsCreateResultSchema,
  TaskSuggestionsDismissParamsSchema,
  TaskSuggestionsDismissResultSchema,
  TaskSuggestionsListParamsSchema,
  TaskSuggestionsListResultSchema,
} from "./task-suggestions.js";
import {
  TasksCancelParamsSchema,
  TasksCancelResultSchema,
  TasksGetParamsSchema,
  TasksGetResultSchema,
  TasksListParamsSchema,
  TasksListResultSchema,
  TaskSummarySchema,
} from "./tasks.js";
import { TerminalProtocolSchemas } from "./terminal-protocol-schemas.js";
import {
  UiClosePaneCommandSchema,
  UiCommandParamsSchema,
  UiCommandResultSchema,
  UiCommandSchema,
  UiFocusCommandSchema,
  UiNavigateCommandSchema,
  UiPanelCommandSchema,
  UiSidebarCommandSchema,
  UiSplitCommandSchema,
} from "./ui-command.js";
import {
  WizardCancelParamsSchema,
  WizardNextParamsSchema,
  WizardNextResultSchema,
  WizardStartParamsSchema,
  WizardStartResultSchema,
  WizardStatusParamsSchema,
  WizardStatusResultSchema,
  WizardStepSchema,
} from "./wizard.js";
import { WorkerAdmissionHandshakeSchema } from "./worker-admission.js";
import {
  WorktreeRecordSchema,
  WorktreesCreateParamsSchema,
  WorktreesGcParamsSchema,
  WorktreesGcResultSchema,
  WorktreesListParamsSchema,
  WorktreesListResultSchema,
  WorktreeBranchSchema,
  WorktreesBranchesParamsSchema,
  WorktreesBranchesResultSchema,
  WorktreesRemoveParamsSchema,
  WorktreesRemoveResultSchema,
  WorktreesRestoreParamsSchema,
} from "./worktrees.js";

/** Public schema registry keyed by stable protocol schema name. */
export const ProtocolSchemas = {
  BoardTab: BoardTabSchema,
  BoardWidget: BoardWidgetSchema,
  BoardSnapshot: BoardSnapshotSchema,
  BoardTabCreateOp: BoardTabCreateOpSchema,
  BoardTabUpdateOp: BoardTabUpdateOpSchema,
  BoardTabDeleteOp: BoardTabDeleteOpSchema,
  BoardTabsReorderOp: BoardTabsReorderOpSchema,
  BoardWidgetMoveOp: BoardWidgetMoveOpSchema,
  BoardWidgetResizeOp: BoardWidgetResizeOpSchema,
  BoardWidgetRemoveOp: BoardWidgetRemoveOpSchema,
  BoardOp: BoardOpSchema,
  BoardMcpAppDescriptor: BoardMcpAppDescriptorSchema,
  BoardWidgetHtmlContent: BoardWidgetHtmlContentSchema,
  BoardWidgetMcpAppContent: BoardWidgetMcpAppContentSchema,
  BoardWidgetContent: BoardWidgetContentSchema,
  BoardGetParams: BoardGetParamsSchema,
  BoardUpdateParams: BoardUpdateParamsSchema,
  BoardWidgetPutParams: BoardWidgetPutParamsSchema,
  BoardWidgetGrantParams: BoardWidgetGrantParamsSchema,
  BoardEventParams: BoardEventParamsSchema,
  BoardChangedEvent: BoardChangedEventSchema,
  BoardFocusTabCommand: BoardFocusTabCommandSchema,
  BoardSetChatDockCommand: BoardSetChatDockCommandSchema,
  BoardCommand: BoardCommandSchema,
  BoardCommandEvent: BoardCommandEventSchema,
  AuthProbeStatus: AuthProbeStatusSchema,
  // Handshake, transport frames, state snapshots, and shared error envelopes.
  ConnectParams: ConnectParamsSchema,
  WorkerAdmissionHandshake: WorkerAdmissionHandshakeSchema,
  HelloOk: HelloOkSchema,
  RequestFrame: RequestFrameSchema,
  ResponseFrame: ResponseFrameSchema,
  EventFrame: EventFrameSchema,
  GatewayFrame: GatewayFrameSchema,
  PresenceEntry: PresenceEntrySchema,
  StateVersion: StateVersionSchema,
  Snapshot: SnapshotSchema,
  ErrorShape: ErrorShapeSchema,
  GatewayErrorDetails: GatewayErrorDetailsSchema,
  GatewaySuspendTaskBlocker: GatewaySuspendTaskBlockerSchema,
  GatewaySuspendBlocker: GatewaySuspendBlockerSchema,
  GatewaySuspendPrepareParams: GatewaySuspendPrepareParamsSchema,
  GatewaySuspendPrepareBusyResult: GatewaySuspendPrepareBusyResultSchema,
  GatewaySuspendPrepareReadyResult: GatewaySuspendPrepareReadyResultSchema,
  GatewaySuspendPrepareResult: GatewaySuspendPrepareResultSchema,
  GatewaySuspendStatusParams: GatewaySuspendStatusParamsSchema,
  GatewaySuspendStatusRunningResult: GatewaySuspendStatusRunningResultSchema,
  GatewaySuspendStatusReadyResult: GatewaySuspendStatusReadyResultSchema,
  GatewaySuspendStatusResult: GatewaySuspendStatusResultSchema,
  GatewaySuspendResumeParams: GatewaySuspendResumeParamsSchema,
  GatewaySuspendResumeResult: GatewaySuspendResumeResultSchema,

  // Environment and agent-facing control RPC payloads.
  EnvironmentStatus: EnvironmentStatusSchema,
  WorkerEnvironmentState: WorkerEnvironmentStateSchema,
  WorkerTunnelStatus: WorkerTunnelStatusSchema,
  WorkerEnvironmentMetadata: WorkerEnvironmentMetadataSchema,
  EnvironmentSummary: EnvironmentSummarySchema,
  EnvironmentsCreateParams: EnvironmentsCreateParamsSchema,
  EnvironmentsCreateResult: EnvironmentsCreateResultSchema,
  EnvironmentsDestroyParams: EnvironmentsDestroyParamsSchema,
  EnvironmentsDestroyResult: EnvironmentsDestroyResultSchema,
  EnvironmentsListParams: EnvironmentsListParamsSchema,
  EnvironmentsListResult: EnvironmentsListResultSchema,
  EnvironmentsStatusParams: EnvironmentsStatusParamsSchema,
  EnvironmentsStatusResult: EnvironmentsStatusResultSchema,
  SystemInfoParams: SystemInfoParamsSchema,
  SystemInfoResult: SystemInfoResultSchema,
  AgentEvent: AgentEventSchema,
  ConversationSendParams: ConversationSendParamsSchema,
  ConversationSendResult: ConversationSendResultSchema,
  ConversationListItem: ConversationListItemSchema,
  ConversationListParams: ConversationListParamsSchema,
  ConversationListResult: ConversationListResultSchema,
  ConversationTurnCancelParams: ConversationTurnCancelParamsSchema,
  ConversationTurnCancelResult: ConversationTurnCancelResultSchema,
  ConversationTurnParams: ConversationTurnParamsSchema,
  ConversationTurnReply: ConversationTurnReplySchema,
  ConversationTurnResult: ConversationTurnResultSchema,
  MessageActionParams: MessageActionParamsSchema,
  SendParams: SendParamsSchema,
  PollParams: PollParamsSchema,
  AgentParams: AgentParamsSchema,
  AgentIdentityParams: AgentIdentityParamsSchema,
  AgentIdentityResult: AgentIdentityResultSchema,
  AgentWaitParams: AgentWaitParamsSchema,
  WakeParams: WakeParamsSchema,
  WorktreeRecord: WorktreeRecordSchema,
  WorktreesListParams: WorktreesListParamsSchema,
  WorktreesListResult: WorktreesListResultSchema,
  WorktreesCreateParams: WorktreesCreateParamsSchema,
  WorktreesRemoveParams: WorktreesRemoveParamsSchema,
  WorktreesRemoveResult: WorktreesRemoveResultSchema,
  WorktreesRestoreParams: WorktreesRestoreParamsSchema,
  WorktreesGcParams: WorktreesGcParamsSchema,
  WorktreesGcResult: WorktreesGcResultSchema,
  WorktreeBranch: WorktreeBranchSchema,
  WorktreesBranchesParams: WorktreesBranchesParamsSchema,
  WorktreesBranchesResult: WorktreesBranchesResultSchema,
  FsDirEntry: FsDirEntrySchema,
  FsListDirParams: FsListDirParamsSchema,
  FsListDirResult: FsListDirResultSchema,

  // Node pairing, invocation, presence, and pending-queue payloads.
  NodePairListParams: NodePairListParamsSchema,
  NodePairApproveParams: NodePairApproveParamsSchema,
  NodePairRejectParams: NodePairRejectParamsSchema,
  NodePairRemoveParams: NodePairRemoveParamsSchema,
  NodeRenameParams: NodeRenameParamsSchema,
  NodeListParams: NodeListParamsSchema,
  NodePluginToolDescriptor: NodePluginToolDescriptorSchema,
  NodePluginToolsUpdateParams: NodePluginToolsUpdateParamsSchema,
  NodeSkillDescriptor: NodeSkillDescriptorSchema,
  NodeSkillsUpdateParams: NodeSkillsUpdateParamsSchema,
  NodePendingAckParams: NodePendingAckParamsSchema,
  NodeDescribeParams: NodeDescribeParamsSchema,
  ...NodeInvokeProtocolSchemas,
  NodeEventParams: NodeEventParamsSchema,
  NodeEventResult: NodeEventResultSchema,
  NodePresenceAlivePayload: NodePresenceAlivePayloadSchema,
  ...NodePresenceProtocolSchemas,
  NodePendingDrainParams: NodePendingDrainParamsSchema,
  NodePendingDrainResult: NodePendingDrainResultSchema,
  NodePendingEnqueueParams: NodePendingEnqueueParamsSchema,
  NodePendingEnqueueResult: NodePendingEnqueueResultSchema,

  // Push and secret-resolution payloads used by mobile/control integrations.
  PushTestParams: PushTestParamsSchema,
  PushTestResult: PushTestResultSchema,
  UiSplitCommand: UiSplitCommandSchema,
  UiClosePaneCommand: UiClosePaneCommandSchema,
  UiFocusCommand: UiFocusCommandSchema,
  UiSidebarCommand: UiSidebarCommandSchema,
  UiPanelCommand: UiPanelCommandSchema,
  UiNavigateCommand: UiNavigateCommandSchema,
  UiCommand: UiCommandSchema,
  UiCommandParams: UiCommandParamsSchema,
  UiCommandResult: UiCommandResultSchema,
  SecretsReloadParams: SecretsReloadParamsSchema,
  SecretsResolveParams: SecretsResolveParamsSchema,
  SecretsResolveAssignment: SecretsResolveAssignmentSchema,
  SecretsResolveResult: SecretsResolveResultSchema,

  // Session lifecycle, message routing, compaction, and usage accounting.
  SessionsListParams: SessionsListParamsSchema,
  SessionCatalogCapabilities: SessionCatalogCapabilitiesSchema,
  SessionCatalogDescriptor: SessionCatalogDescriptorSchema,
  SessionCatalogSession: SessionCatalogSessionSchema,
  SessionCatalogHost: SessionCatalogHostSchema,
  SessionCatalog: SessionCatalogSchema,
  SessionCatalogTranscriptItem: SessionCatalogTranscriptItemSchema,
  SessionsCatalogListParams: SessionsCatalogListParamsSchema,
  SessionsCatalogListResult: SessionsCatalogListResultSchema,
  SessionsCatalogReadParams: SessionsCatalogReadParamsSchema,
  SessionsCatalogReadResult: SessionsCatalogReadResultSchema,
  SessionsCatalogContinueParams: SessionsCatalogContinueParamsSchema,
  SessionsCatalogContinueResult: SessionsCatalogContinueResultSchema,
  SessionsCatalogArchiveParams: SessionsCatalogArchiveParamsSchema,
  SessionsCatalogArchiveResult: SessionsCatalogArchiveResultSchema,
  SessionsCleanupParams: SessionsCleanupParamsSchema,
  SessionsPreviewParams: SessionsPreviewParamsSchema,
  SessionsDescribeParams: SessionsDescribeParamsSchema,
  SessionsResolveParams: SessionsResolveParamsSchema,
  SessionsSearchHit: SessionsSearchHitSchema,
  SessionsSearchParams: SessionsSearchParamsSchema,
  SessionsSearchResult: SessionsSearchResultSchema,
  SessionCompactionCheckpoint: SessionCompactionCheckpointSchema,
  SessionOperationEvent: SessionOperationEventSchema,
  ...SessionPlacementProtocolSchemas,
  SessionsCompactionListParams: SessionsCompactionListParamsSchema,
  SessionsCompactionGetParams: SessionsCompactionGetParamsSchema,
  SessionsCompactionBranchParams: SessionsCompactionBranchParamsSchema,
  SessionsCompactionRestoreParams: SessionsCompactionRestoreParamsSchema,
  SessionsCompactionListResult: SessionsCompactionListResultSchema,
  SessionsCompactionGetResult: SessionsCompactionGetResultSchema,
  SessionsCompactionBranchResult: SessionsCompactionBranchResultSchema,
  SessionsCompactionRestoreResult: SessionsCompactionRestoreResultSchema,
  SessionsRewindParams: SessionsRewindParamsSchema,
  SessionsRewindResult: SessionsRewindResultSchema,
  SessionsForkParams: SessionsForkParamsSchema,
  SessionsForkResult: SessionsForkResultSchema,
  SessionFileBrowserEntry: SessionFileBrowserEntrySchema,
  SessionFileBrowserResult: SessionFileBrowserResultSchema,
  SessionFileKind: SessionFileKindSchema,
  SessionFileEntry: SessionFileEntrySchema,
  SessionFileRelevance: SessionFileRelevanceSchema,
  SessionsFilesListParams: SessionsFilesListParamsSchema,
  SessionsFilesListResult: SessionsFilesListResultSchema,
  SessionsFilesGetParams: SessionsFilesGetParamsSchema,
  SessionsFilesGetResult: SessionsFilesGetResultSchema,
  SessionsFilesRevealParams: SessionsFilesRevealParamsSchema,
  SessionsFilesRevealResult: SessionsFilesRevealResultSchema,
  SessionsFilesSetParams: SessionsFilesSetParamsSchema,
  SessionsFilesSetResult: SessionsFilesSetResultSchema,
  SessionDiffFileStatus: SessionDiffFileStatusSchema,
  SessionDiffFile: SessionDiffFileSchema,
  SessionsDiffParams: SessionsDiffParamsSchema,
  SessionsDiffResult: SessionsDiffResultSchema,
  SessionWorktreeInfo: SessionWorktreeInfoSchema,
  SessionsCreateParams: SessionsCreateParamsSchema,
  SessionsCreateResult: SessionsCreateResultSchema,
  SessionsSendParams: SessionsSendParamsSchema,
  SessionsMessagesSubscribeParams: SessionsMessagesSubscribeParamsSchema,
  SessionsMessagesUnsubscribeParams: SessionsMessagesUnsubscribeParamsSchema,
  SessionsAbortParams: SessionsAbortParamsSchema,
  SessionsPatchParams: SessionsPatchParamsSchema,
  SessionsPluginPatchParams: SessionsPluginPatchParamsSchema,
  SessionsPluginPatchResult: SessionsPluginPatchResultSchema,
  SessionsResetParams: SessionsResetParamsSchema,
  SessionsDeleteParams: SessionsDeleteParamsSchema,
  SessionGroup: SessionGroupSchema,
  SessionsGroupsListParams: SessionsGroupsListParamsSchema,
  SessionsGroupsListResult: SessionsGroupsListResultSchema,
  SessionsGroupsPutParams: SessionsGroupsPutParamsSchema,
  SessionsGroupsRenameParams: SessionsGroupsRenameParamsSchema,
  SessionsGroupsDeleteParams: SessionsGroupsDeleteParamsSchema,
  SessionsGroupsMutationResult: SessionsGroupsMutationResultSchema,
  SessionsCompactParams: SessionsCompactParamsSchema,
  SessionsUsageParams: SessionsUsageParamsSchema,

  // Audit/task ledgers and config/wizard setup payloads.
  AuditActivityAgentRunV1: AuditActivityAgentRunV1Schema,
  AuditActivityToolActionV1: AuditActivityToolActionV1Schema,
  AuditActivityInboundMessageV1: AuditActivityInboundMessageV1Schema,
  AuditActivityOutboundMessageV1: AuditActivityOutboundMessageV1Schema,
  AuditActivityEventV1: AuditActivityEventV1Schema,
  AuditActivityListParams: AuditActivityListParamsSchema,
  AuditActivityListResult: AuditActivityListResultSchema,
  AuditEvent: AuditEventSchema,
  AuditListParams: AuditListParamsSchema,
  AuditListResult: AuditListResultSchema,
  TaskSuggestion: TaskSuggestionSchema,
  TaskSuggestionEvent: TaskSuggestionEventSchema,
  TaskSuggestionResolution: TaskSuggestionResolutionSchema,
  TaskSuggestionsAcceptParams: TaskSuggestionsAcceptParamsSchema,
  TaskSuggestionsAcceptResult: TaskSuggestionsAcceptResultSchema,
  TaskSuggestionsCreateParams: TaskSuggestionsCreateParamsSchema,
  TaskSuggestionsCreateResult: TaskSuggestionsCreateResultSchema,
  TaskSuggestionsDismissParams: TaskSuggestionsDismissParamsSchema,
  TaskSuggestionsDismissResult: TaskSuggestionsDismissResultSchema,
  TaskSuggestionsListParams: TaskSuggestionsListParamsSchema,
  TaskSuggestionsListResult: TaskSuggestionsListResultSchema,
  TaskSummary: TaskSummarySchema,
  TasksListParams: TasksListParamsSchema,
  TasksListResult: TasksListResultSchema,
  TasksGetParams: TasksGetParamsSchema,
  TasksGetResult: TasksGetResultSchema,
  TasksCancelParams: TasksCancelParamsSchema,
  TasksCancelResult: TasksCancelResultSchema,
  ConfigGetParams: ConfigGetParamsSchema,
  ConfigSetParams: ConfigSetParamsSchema,
  ConfigApplyParams: ConfigApplyParamsSchema,
  ConfigPatchParams: ConfigPatchParamsSchema,
  ConfigSchemaParams: ConfigSchemaParamsSchema,
  ConfigSchemaLookupParams: ConfigSchemaLookupParamsSchema,
  ConfigSchemaResponse: ConfigSchemaResponseSchema,
  ConfigSchemaLookupResult: ConfigSchemaLookupResultSchema,
  SystemAgentChatParams: SystemAgentChatParamsSchema,
  SystemAgentChatResult: SystemAgentChatResultSchema,
  SystemAgentChatHistoryParams: SystemAgentChatHistoryParamsSchema,
  SystemAgentChatHistoryTurn: SystemAgentChatHistoryTurnSchema,
  SystemAgentChatHistoryResult: SystemAgentChatHistoryResultSchema,
  SystemChangeEntry: SystemChangeEntrySchema,
  SystemChangeKind: SystemChangeKindSchema,
  SystemChangeSource: SystemChangeSourceSchema,
  SystemChangesListParams: SystemChangesListParamsSchema,
  SystemChangesListResult: SystemChangesListResultSchema,
  SystemAgentSetupDetectParams: SystemAgentSetupDetectParamsSchema,
  SystemAgentSetupDetectResult: SystemAgentSetupDetectResultSchema,
  SystemAgentSetupVerifyParams: SystemAgentSetupVerifyParamsSchema,
  SystemAgentSetupVerifyResult: SystemAgentSetupVerifyResultSchema,
  SystemAgentSetupActivateParams: SystemAgentSetupActivateParamsSchema,
  SystemAgentSetupActivateResult: SystemAgentSetupActivateResultSchema,
  SystemAgentSetupAuthStartParams: SystemAgentSetupAuthStartParamsSchema,
  SystemAgentSetupAuthStartResult: SystemAgentSetupAuthStartResultSchema,
  WizardStartParams: WizardStartParamsSchema,
  WizardNextParams: WizardNextParamsSchema,
  WizardCancelParams: WizardCancelParamsSchema,
  WizardStatusParams: WizardStatusParamsSchema,
  WizardStep: WizardStepSchema,
  WizardNextResult: WizardNextResultSchema,
  WizardStartResult: WizardStartResultSchema,
  WizardStatusResult: WizardStatusResultSchema,

  // Realtime Talk client/session events and channel control payloads.
  TalkModeParams: TalkModeParamsSchema,
  TalkEvent: TalkEventSchema,
  TalkCatalogParams: TalkCatalogParamsSchema,
  TalkCatalogResult: TalkCatalogResultSchema,
  TalkClientCreateParams: TalkClientCreateParamsSchema,
  TalkClientCreateResult: TalkClientCreateResultSchema,
  TalkClientCloseParams: TalkClientCloseParamsSchema,
  TalkClientMutationResult: TalkClientMutationResultSchema,
  TalkClientSteerParams: TalkClientSteerParamsSchema,
  TalkAgentControlResult: TalkAgentControlResultSchema,
  TalkClientToolCallParams: TalkClientToolCallParamsSchema,
  TalkClientToolCallResult: TalkClientToolCallResultSchema,
  TalkClientTranscriptParams: TalkClientTranscriptParamsSchema,
  TalkConfigParams: TalkConfigParamsSchema,
  TalkConfigResult: TalkConfigResultSchema,
  TalkSessionAppendAudioParams: TalkSessionAppendAudioParamsSchema,
  TalkSessionAcknowledgeMarkParams: TalkSessionAcknowledgeMarkParamsSchema,
  TalkSessionCancelOutputParams: TalkSessionCancelOutputParamsSchema,
  TalkSessionCancelTurnParams: TalkSessionCancelTurnParamsSchema,
  TalkSessionCreateParams: TalkSessionCreateParamsSchema,
  TalkSessionCreateResult: TalkSessionCreateResultSchema,
  TalkSessionJoinParams: TalkSessionJoinParamsSchema,
  TalkSessionJoinResult: TalkSessionJoinResultSchema,
  TalkSessionTurnParams: TalkSessionTurnParamsSchema,
  TalkSessionTurnResult: TalkSessionTurnResultSchema,
  TalkSessionSteerParams: TalkSessionSteerParamsSchema,
  TalkSessionSubmitToolResultParams: TalkSessionSubmitToolResultParamsSchema,
  TalkSessionCloseParams: TalkSessionCloseParamsSchema,
  TalkSessionOkResult: TalkSessionOkResultSchema,
  TalkSpeakParams: TalkSpeakParamsSchema,
  TalkSpeakResult: TalkSpeakResultSchema,
  TtsSpeakParams: TtsSpeakParamsSchema,
  TtsSpeakResult: TtsSpeakResultSchema,
  ChannelsStatusParams: ChannelsStatusParamsSchema,
  ChannelsStatusResult: ChannelsStatusResultSchema,
  ChannelsStartParams: ChannelsStartParamsSchema,
  ChannelsStopParams: ChannelsStopParamsSchema,
  ChannelsLogoutParams: ChannelsLogoutParamsSchema,
  WebLoginStartParams: WebLoginStartParamsSchema,
  WebLoginWaitParams: WebLoginWaitParamsSchema,

  // Agent files, artifacts, model catalogs, commands, tools, and skill workshop.
  AgentSummary: AgentSummarySchema,
  AgentsCreateParams: AgentsCreateParamsSchema,
  AgentsCreateResult: AgentsCreateResultSchema,
  AgentsUpdateParams: AgentsUpdateParamsSchema,
  AgentsUpdateResult: AgentsUpdateResultSchema,
  AgentsDeleteParams: AgentsDeleteParamsSchema,
  AgentsDeleteResult: AgentsDeleteResultSchema,
  AgentsFileEntry: AgentsFileEntrySchema,
  AgentsFilesListParams: AgentsFilesListParamsSchema,
  AgentsFilesListResult: AgentsFilesListResultSchema,
  AgentsFilesGetParams: AgentsFilesGetParamsSchema,
  AgentsFilesGetResult: AgentsFilesGetResultSchema,
  AgentsFilesSetParams: AgentsFilesSetParamsSchema,
  AgentsFilesSetResult: AgentsFilesSetResultSchema,
  AgentsWorkspaceEntry: AgentsWorkspaceEntrySchema,
  AgentsWorkspaceFile: AgentsWorkspaceFileSchema,
  AgentsWorkspaceListParams: AgentsWorkspaceListParamsSchema,
  AgentsWorkspaceListResult: AgentsWorkspaceListResultSchema,
  AgentsWorkspaceGetParams: AgentsWorkspaceGetParamsSchema,
  AgentsWorkspaceGetResult: AgentsWorkspaceGetResultSchema,
  ArtifactSummary: ArtifactSummarySchema,
  ArtifactsListParams: ArtifactsListParamsSchema,
  ArtifactsListResult: ArtifactsListResultSchema,
  ArtifactsGetParams: ArtifactsGetParamsSchema,
  ArtifactsGetResult: ArtifactsGetResultSchema,
  ArtifactsDownloadParams: ArtifactsDownloadParamsSchema,
  ArtifactsDownloadResult: ArtifactsDownloadResultSchema,
  AgentsListParams: AgentsListParamsSchema,
  AgentsListResult: AgentsListResultSchema,
  ModelChoice: ModelChoiceSchema,
  ModelsListParams: ModelsListParamsSchema,
  ModelsListResult: ModelsListResultSchema,
  ModelsProbeParams: ModelsProbeParamsSchema,
  ModelsProbeTargetResult: ModelsProbeTargetResultSchema,
  ModelsProbeResult: ModelsProbeResultSchema,
  CommandEntry: CommandEntrySchema,
  CommandsListParams: CommandsListParamsSchema,
  CommandsListResult: CommandsListResultSchema,
  SkillsStatusParams: SkillsStatusParamsSchema,
  ToolsCatalogParams: ToolsCatalogParamsSchema,
  ToolCatalogProfile: ToolCatalogProfileSchema,
  ToolCatalogEntry: ToolCatalogEntrySchema,
  ToolCatalogGroup: ToolCatalogGroupSchema,
  ToolsCatalogResult: ToolsCatalogResultSchema,
  ToolsEffectiveParams: ToolsEffectiveParamsSchema,
  ToolsEffectiveEntry: ToolsEffectiveEntrySchema,
  ToolsEffectiveGroup: ToolsEffectiveGroupSchema,
  ToolsEffectiveNotice: ToolsEffectiveNoticeSchema,
  ToolsEffectiveResult: ToolsEffectiveResultSchema,
  ToolsInvokeParams: ToolsInvokeParamsSchema,
  ToolsInvokeError: ToolsInvokeErrorSchema,
  ToolsInvokeResult: ToolsInvokeResultSchema,
  SkillsBinsParams: SkillsBinsParamsSchema,
  SkillsBinsResult: SkillsBinsResultSchema,
  SkillsSearchParams: SkillsSearchParamsSchema,
  SkillsSearchResult: SkillsSearchResultSchema,
  SkillsDetailParams: SkillsDetailParamsSchema,
  SkillsDetailResult: SkillsDetailResultSchema,
  SkillsCuratorActionParams: SkillsCuratorActionParamsSchema,
  SkillsCuratorActionResult: SkillsCuratorActionResultSchema,
  SkillsCuratorStatusParams: SkillsCuratorStatusParamsSchema,
  SkillsCuratorStatusResult: SkillsCuratorStatusResultSchema,
  ...SkillWorkshopProtocolSchemas,
  SkillsProposalInspectParams: SkillsProposalInspectParamsSchema,
  SkillsProposalInspectResult: SkillsProposalInspectResultSchema,
  SkillsProposalCreateParams: SkillsProposalCreateParamsSchema,
  SkillsProposalUpdateParams: SkillsProposalUpdateParamsSchema,
  SkillsProposalReviseParams: SkillsProposalReviseParamsSchema,
  SkillsProposalRequestRevisionParams: SkillsProposalRequestRevisionParamsSchema,
  SkillsProposalRequestRevisionResult: SkillsProposalRequestRevisionResultSchema,
  SkillsProposalActionParams: SkillsProposalActionParamsSchema,
  SkillsProposalApplyResult: SkillsProposalApplyResultSchema,
  SkillsProposalRecordResult: SkillsProposalRecordResultSchema,
  SkillsSecurityVerdictsParams: SkillsSecurityVerdictsParamsSchema,
  SkillsSecurityVerdictsResult: SkillsSecurityVerdictsResultSchema,
  SkillsSkillCardParams: SkillsSkillCardParamsSchema,
  SkillsSkillCardResult: SkillsSkillCardResultSchema,
  SkillsUploadBeginParams: SkillsUploadBeginParamsSchema,
  SkillsUploadChunkParams: SkillsUploadChunkParamsSchema,
  SkillsUploadCommitParams: SkillsUploadCommitParamsSchema,
  SkillsInstallParams: SkillsInstallParamsSchema,
  SkillsUpdateParams: SkillsUpdateParamsSchema,
  // Scheduler, logs, approval, plugin control, device, chat, and lifecycle events.
  CronJob: CronJobSchema,
  CronListParams: CronListParamsSchema,
  CronStatusParams: CronStatusParamsSchema,
  CronGetParams: CronGetParamsSchema,
  CronAddParams: CronAddParamsSchema,
  CronAddResult: CronAddResultSchema,
  CronDeclarativeAddResult: CronDeclarativeAddResultSchema,
  CronUpdateParams: CronUpdateParamsSchema,
  CronRemoveParams: CronRemoveParamsSchema,
  CronRunParams: CronRunParamsSchema,
  CronRunsParams: CronRunsParamsSchema,
  CronRunLogEntry: CronRunLogEntrySchema,
  ...LogMigrationProtocolSchemas,
  ...TerminalProtocolSchemas,
  ApprovalKind: ApprovalKindSchema,
  ApprovalDecision: ApprovalDecisionSchema,
  ApprovalAllowDecision: ApprovalAllowDecisionSchema,
  ApprovalAllowedReason: ApprovalAllowedReasonSchema,
  ApprovalDeniedReason: ApprovalDeniedReasonSchema,
  ApprovalExpiredReason: ApprovalExpiredReasonSchema,
  ApprovalCancelledReason: ApprovalCancelledReasonSchema,
  PluginApprovalSeverity: PluginApprovalSeveritySchema,
  ExecApprovalPresentation: ExecApprovalPresentationSchema,
  PluginApprovalPresentation: PluginApprovalPresentationSchema,
  SystemAgentApprovalPresentation: SystemAgentApprovalPresentationSchema,
  ApprovalPresentation: ApprovalPresentationSchema,
  PendingApprovalSnapshot: PendingApprovalSnapshotSchema,
  AllowedApprovalSnapshot: AllowedApprovalSnapshotSchema,
  DeniedApprovalSnapshot: DeniedApprovalSnapshotSchema,
  ExpiredApprovalSnapshot: ExpiredApprovalSnapshotSchema,
  CancelledApprovalSnapshot: CancelledApprovalSnapshotSchema,
  ApprovalSnapshot: ApprovalSnapshotSchema,
  ApprovalTerminalReason: ApprovalTerminalReasonSchema,
  TerminalApprovalSnapshot: TerminalApprovalSnapshotSchema,
  ApprovalGetParams: ApprovalGetParamsSchema,
  ApprovalGetResult: ApprovalGetResultSchema,
  ApprovalHistoryParams: ApprovalHistoryParamsSchema,
  ApprovalHistoryResult: ApprovalHistoryResultSchema,
  ApprovalResolveParams: ApprovalResolveParamsSchema,
  ApprovalResolveResult: ApprovalResolveResultSchema,
  PendingSessionApprovalEvent: PendingSessionApprovalEventSchema,
  TerminalSessionApprovalEvent: TerminalSessionApprovalEventSchema,
  SessionApprovalEvent: SessionApprovalEventSchema,
  SessionApprovalReplay: SessionApprovalReplaySchema,
  ExecApprovalsGetParams: ExecApprovalsGetParamsSchema,
  ExecApprovalsSetParams: ExecApprovalsSetParamsSchema,
  ExecApprovalsNodeGetParams: ExecApprovalsNodeGetParamsSchema,
  ExecApprovalsNodeSnapshot: ExecApprovalsNodeSnapshotSchema,
  ExecApprovalsNodeSetParams: ExecApprovalsNodeSetParamsSchema,
  ExecApprovalsSnapshot: ExecApprovalsSnapshotSchema,
  ExecApprovalGetParams: ExecApprovalGetParamsSchema,
  ExecApprovalRequestParams: ExecApprovalRequestParamsSchema,
  ExecApprovalResolveParams: ExecApprovalResolveParamsSchema,
  QuestionOption: QuestionOptionSchema,
  Question: QuestionSchema,
  QuestionRequestQuestion: QuestionRequestQuestionSchema,
  QuestionAnswers: QuestionAnswersSchema,
  QuestionStatus: QuestionStatusSchema,
  QuestionRecord: QuestionRecordSchema,
  QuestionRequestParams: QuestionRequestParamsSchema,
  QuestionRequestResult: QuestionRequestResultSchema,
  QuestionWaitAnswerParams: QuestionWaitAnswerParamsSchema,
  QuestionWaitAnswerResult: QuestionWaitAnswerResultSchema,
  QuestionResolveParams: QuestionResolveParamsSchema,
  QuestionResolveResult: QuestionResolveResultSchema,
  QuestionGetParams: QuestionGetParamsSchema,
  QuestionGetResult: QuestionGetResultSchema,
  QuestionListParams: QuestionListParamsSchema,
  QuestionListResult: QuestionListResultSchema,
  // QuestionRequestedEvent is a TS-only alias of QuestionRecord; registering both
  // names makes native codegen reference a type it never emits.
  QuestionResolvedEvent: QuestionResolvedEventSchema,
  PluginApprovalRequestParams: PluginApprovalRequestParamsSchema,
  PluginApprovalResolveParams: PluginApprovalResolveParamsSchema,
  PluginCatalogClawHubInstall: PluginCatalogClawHubInstallSchema,
  PluginCatalogEntry: PluginCatalogEntrySchema,
  PluginCatalogInstallAction: PluginCatalogInstallActionSchema,
  PluginCatalogOfficialInstall: PluginCatalogOfficialInstallSchema,
  PluginControlUiDescriptor: PluginControlUiDescriptorSchema,
  PluginSearchPackage: PluginSearchPackageSchema,
  PluginSearchResultEntry: PluginSearchResultEntrySchema,
  PluginsInstallParams: PluginsInstallParamsSchema,
  PluginsInstallResult: PluginsInstallResultSchema,
  PluginsListParams: PluginsListParamsSchema,
  PluginsListResult: PluginsListResultSchema,
  PluginsRefreshParams: PluginsRefreshParamsSchema,
  PluginsRefreshResult: PluginsRefreshResultSchema,
  PluginsSearchParams: PluginsSearchParamsSchema,
  PluginsSearchResult: PluginsSearchResultSchema,
  PluginsSessionActionFailureResult: PluginsSessionActionFailureResultSchema,
  PluginsSessionActionParams: PluginsSessionActionParamsSchema,
  PluginsSessionActionResult: PluginsSessionActionResultSchema,
  PluginsSessionActionSuccessResult: PluginsSessionActionSuccessResultSchema,
  PluginsSetEnabledParams: PluginsSetEnabledParamsSchema,
  PluginsSetEnabledResult: PluginsSetEnabledResultSchema,
  PluginsUiDescriptorsParams: PluginsUiDescriptorsParamsSchema,
  PluginsUiDescriptorsResult: PluginsUiDescriptorsResultSchema,
  PluginsUninstallParams: PluginsUninstallParamsSchema,
  PluginsUninstallResult: PluginsUninstallResultSchema,
  DevicePairListParams: DevicePairListParamsSchema,
  DevicePairApproveParams: DevicePairApproveParamsSchema,
  DevicePairRejectParams: DevicePairRejectParamsSchema,
  DevicePairRemoveParams: DevicePairRemoveParamsSchema,
  DevicePairSetupCodeParams: DevicePairSetupCodeParamsSchema,
  DevicePairSetupCodeResult: DevicePairSetupCodeResultSchema,
  DevicePairRenameParams: DevicePairRenameParamsSchema,
  DeviceTokenRotateParams: DeviceTokenRotateParamsSchema,
  DeviceTokenRevokeParams: DeviceTokenRevokeParamsSchema,
  DevicePairRequestedEvent: DevicePairRequestedEventSchema,
  DevicePairResolvedEvent: DevicePairResolvedEventSchema,
  ChatHistoryParams: ChatHistoryParamsSchema,
  ChatMetadataParams: ChatMetadataParamsSchema,
  ChatMessageGetParams: ChatMessageGetParamsSchema,
  ChatMessageGetResult: ChatMessageGetResultSchema,
  ChatToolTitlesParams: ChatToolTitlesParamsSchema,
  ChatToolTitlesResult: ChatToolTitlesResultSchema,
  ChatSendParams: ChatSendParamsSchema,
  ChatAbortParams: ChatAbortParamsSchema,
  ChatInjectParams: ChatInjectParamsSchema,
  ChatDeltaEvent: ChatDeltaEventSchema,
  ChatFinalEvent: ChatFinalEventSchema,
  ChatAbortedEvent: ChatAbortedEventSchema,
  ChatErrorEvent: ChatErrorEventSchema,
  ChatEvent: ChatEventSchema,
  UpdateStatusParams: UpdateStatusParamsSchema,
  UpdateRunParams: UpdateRunParamsSchema,
  TickEvent: TickEventSchema,
  ShutdownEvent: ShutdownEventSchema,
} satisfies Record<string, TSchema>;
export {
  MIN_CLIENT_PROTOCOL_VERSION,
  MIN_NODE_PROTOCOL_VERSION,
  MIN_PROBE_PROTOCOL_VERSION,
  PROTOCOL_VERSION,
} from "../version.js";
/* oxlint-disable max-lines -- TODO: split this grandfathered oversized file. */
