/** OpenClaw-owned agent runtime facade; the plugin SDK module owns the adapter. */
export {
  Agent,
  bashExecutionToText,
  buildSessionContext,
  calculateContextTokens,
  collectEntriesForBranchSummaryFromBranches,
  compact,
  estimateContextTokens,
  estimateTokens,
  findCutPoint,
  findTurnStartIndex,
  generateBranchSummary,
  generateSummary,
  getLastAssistantUsage,
  openClawAgentCoreRuntime,
  prepareBranchEntries,
  prepareCompaction,
  runAgentLoop,
  serializeConversation,
  shouldCompact,
  uuidv7,
  BRANCH_SUMMARY_PREFIX,
  BRANCH_SUMMARY_SUFFIX,
  COMPACTION_SUMMARY_PREFIX,
  COMPACTION_SUMMARY_SUFFIX,
  DEFAULT_COMPACTION_SETTINGS,
} from "../../plugin-sdk/agent-core.js";
export type {
  AfterToolCallContext,
  AfterToolCallResult,
  AgentEvent,
  AgentMessage,
  AgentOptions,
  AgentState,
  AgentTool,
  AgentToolProgress,
  AgentToolResult,
  AgentToolUpdateCallback,
  BashExecutionMessage,
  BranchPreparation,
  BranchSummaryDetails,
  BranchSummaryResult,
  CompactionDetails,
  CompactionPreparation,
  CompactionResult,
  CompactionSettings,
  ContextUsageEstimate,
  FileOperations,
  Result,
  SessionTreeEntry,
  StreamFn,
  ThinkingLevel,
  ToolExecutionMode,
} from "../../plugin-sdk/agent-core.js";
