// Teams web selectors validated against live guest surfaces.
// Prefer product-owned ids/data-tids; text remains a fallback for localized drift.
export const TEAMS_MEETING_SELECTORS = {
  continueInBrowser: [
    '[data-tid="joinOnWeb"]',
    '[data-tid="joinOnWebButton"]',
    'button[data-tid="continue-on-browser"]',
  ],
  guestName: [
    'input[data-tid="prejoin-display-name-input"]',
    '[data-tid="prejoin-display-name-input"] input',
    'input[data-tid="guest-name-input"]',
  ],
  join: [
    'button[data-tid="prejoin-join-button"]',
    '[data-tid="prejoin-join-button"] button',
    'button[data-tid="join-now"]',
    'button[data-tid="join-button"]',
  ],
  microphone: [
    'button[data-tid="toggle-mute"]',
    '[data-tid="toggle-mute"] button',
    'input[data-tid="toggle-mute"]',
    '[data-tid="toggle-mute"][role="switch"]',
    'button[data-tid="microphone-button"]',
  ],
  camera: [
    'button[data-tid="toggle-video"]',
    '[data-tid="toggle-video"] button',
    'input[data-tid="toggle-video"]',
    '[data-tid="toggle-video"][role="switch"]',
    'button[data-tid="camera-button"]',
  ],
  deviceSettings: [
    "button#audio-button-configure",
    'button[aria-label="Open audio options"]',
    'button[data-tid="prejoin-device-settings-button"]',
    'button[data-tid="device-settings-button"]',
    'button[data-tid="audio-device-settings-button"]',
  ],
  microphoneDevice: [
    'button[data-tid="selected-microphone-display"]',
    '[data-tid="microphone-select"]',
    '[data-tid="audio-device-input"]',
    '[data-tid="device-settings-microphone"] [role="combobox"]',
    'select[data-tid="microphone-select"]',
  ],
  microphoneDeviceMenu: ['[data-tid="microphone-settings"][role="listbox"]'],
  selectedMicrophoneDevice: ["option:checked", '[role="option"][aria-selected="true"]'],
  audioDeviceOptions: ["option", '[role="option"]'],
  leave: [
    "button#hangup-button",
    'button[data-tid="call-hangup"]',
    '[data-tid="call-hangup"] button',
    'button[data-tid="hangup-button"]',
    'button[data-tid="call-hangup-button"]',
  ],
  leaveConfirmation: [
    'button[data-tid="confirm-leave-button"]',
    'button[data-tid="leave-meeting-confirm"]',
    'button[data-tid="leave-call-confirm"]',
  ],
  postCall: [
    'button[data-tid="anon-meeting-end-screen-rejoin-button"]',
    '[data-tid="call-ended-screen"]',
    '[data-tid="post-call-screen"]',
    'button[data-tid="prejoin-rejoin-button"]',
  ],
  lobby: ['[data-tid="lobby-screen"]', '[data-tid="lobby-waiting-screen"]'],
  signIn: [
    'button[data-tid="signin-button"]',
    'button[data-tid="sign-in-button"]',
    '[data-tid="auth-signin"]',
  ],
  permissionPrompt: [
    '[data-tid="device-permission-prompt"]',
    '[data-tid="media-permission-prompt"]',
    '[data-tid="browser-permission-error"]',
  ],
  moreActions: ['button[aria-label="More"]'],
  captions: ["button#closed-captions-button", '[role="menuitem"][title*="captions" i]'],
  captionsOff: [
    'button[data-tid="closed-captions-turn-off-button"]',
    "button#captions-panel-dismiss-button",
  ],
  captionRenderer: ['[data-tid="closed-caption-renderer-wrapper"]'],
  captionContent: ['[data-tid="closed-caption-v2-virtual-list-content"]'],
  captionRows: ['div[role="log"]'],
  captionAuthor: ['[data-tid="author"]'],
  captionText: ['[data-tid="closed-caption-text"]'],
} as const;
