import type { MatrixQaObservedEvent } from "../../substrate/events.js";

export type MatrixQaReplyArtifact = {
  bodyPreview?: string;
  eventId: string;
  mentions?: MatrixQaObservedEvent["mentions"];
  relatesTo?: MatrixQaObservedEvent["relatesTo"];
  sender?: string;
  tokenMatched?: boolean;
};

export type MatrixQaCanaryArtifact = {
  driverEventId: string;
  reply: MatrixQaReplyArtifact;
  token: string;
};

export type MatrixQaScenarioArtifacts = {
  accepted?: MatrixQaScenarioArtifacts;
  attachments?: Array<{
    eventId: string;
    filename?: string;
    kind?: string;
    label: string;
    msgtype?: string;
  }>;
  attachmentCaptionPreview?: string;
  attachmentBodyPreview?: string;
  attachmentEventId?: string;
  attachmentFilename?: string;
  attachmentKind?: string;
  attachmentMsgtype?: string;
  actorUserId?: string;
  blocked?: MatrixQaScenarioArtifacts;
  catchupDriverEventId?: string;
  catchupReply?: MatrixQaReplyArtifact;
  catchupToken?: string;
  dedupeCommitObserved?: boolean;
  duplicateWindowMs?: number;
  driverEventId?: string;
  editEventId?: string;
  editedToken?: string;
  expectedNoReplyWindowMs?: number;
  firstDriverEventId?: string;
  firstReply?: MatrixQaReplyArtifact;
  firstToken?: string;
  freshDriverEventId?: string;
  freshReply?: MatrixQaReplyArtifact;
  freshToken?: string;
  incrementalDriverEventId?: string;
  incrementalReply?: MatrixQaReplyArtifact;
  incrementalToken?: string;
  originalDriverEventId?: string;
  originalReply?: MatrixQaReplyArtifact;
  originalToken?: string;
  reactionEmoji?: string;
  reactionEventId?: string;
  reactionTargetEventId?: string;
  redactionEventId?: string;
  reply?: MatrixQaReplyArtifact;
  replies?: Array<{
    eventId: string;
    label: string;
    token: string;
    tokenMatched?: boolean;
  }>;
  recoveredDriverEventId?: string;
  recoveredReply?: MatrixQaReplyArtifact;
  rootEventId?: string;
  roomKey?: string;
  roomId?: string;
  restartSignal?: string;
  secondDriverEventId?: string;
  secondReply?: MatrixQaReplyArtifact;
  secondToken?: string;
  staleSyncCursor?: string;
  subagentCompletion?: MatrixQaReplyArtifact;
  subagentIntro?: MatrixQaReplyArtifact;
  threadDriverEventId?: string;
  threadReply?: MatrixQaReplyArtifact;
  threadRootEventId?: string;
  threadToken?: string;
  token?: string;
  topLevelDriverEventId?: string;
  topLevelReply?: MatrixQaReplyArtifact;
  topLevelToken?: string;
  triggerBody?: string;
  membershipJoinEventId?: string;
  membershipLeaveEventId?: string;
  noticeBodyPreview?: string;
  noticeEventId?: string;
  previewBodyPreview?: string;
  previewEventId?: string;
  blockEventIds?: string[];
  bootstrapActor?: "driver" | "observer" | "sut";
  bootstrapErrorPreview?: string;
  bootstrapSuccess?: boolean;
  backupCreatedVersion?: string | null;
  backupDeletedHttpStatus?: number;
  backupPreviousVersion?: string | null;
  backupRestored?: boolean;
  backupReset?: boolean;
  completedVerificationId?: string;
  completedVerificationIds?: string[];
  currentDeviceId?: string | null;
  accountRoot?: string;
  corruptedPath?: string;
  deletedSyncStorePath?: string;
  deletedDeviceIds?: string[];
  deletedDeviceId?: string;
  deletedBackupVersion?: string | null;
  faultedEndpoint?: string;
  faultHitCount?: number;
  faultRuleId?: string;
  historyEventId?: string;
  observerRecoveryDeviceId?: string;
  qrBytes?: number;
  recoveryDeviceId?: string;
  recoveryKeyPreserved?: boolean;
  recoveryKeyId?: string | null;
  recoveryKeyStored?: boolean;
  rotatedRecoveryKeyId?: string | null;
  remainingDeviceIds?: string[];
  restoreError?: string;
  restoreErrorAfterDelete?: string;
  restoreExitCode?: number;
  restoreImported?: number;
  restoreTotal?: number;
  sasEmoji?: string[];
  secondaryDeviceId?: string;
  seededEventId?: string;
  replyEventId?: string;
  statusError?: string;
  statusExitCode?: number;
  serverDeviceKnown?: boolean | null;
  selfVerificationTransactionId?: string | null;
  transportInterruption?: string;
  verificationRoomId?: string;
  joinedRoomId?: string;
  localEventId?: string;
  verificationExitCode?: number;
};

export type MatrixQaScenarioExecution = {
  artifacts?: MatrixQaScenarioArtifacts;
  details: string;
};
