/**
 * Discovers static asset copy specs from extension package metadata.
 */
export function discoverStaticExtensionAssets(params?: Record<string, unknown>): {
  pluginDir: unknown;
  src: string;
  dest: string;
}[];
/**
 * Lists generated dist output paths for declared static extension assets.
 */
export function listStaticExtensionAssetOutputs(params?: Record<string, unknown>): unknown;
/**
 * Lists source file paths for declared static extension assets.
 */
export function listStaticExtensionAssetSources(params?: Record<string, unknown>): unknown;
/**
 * Lists source-tree outputs generated by extension asset build hooks.
 */
export function listGeneratedExtensionAssetSources(params?: Record<string, unknown>): string[];
/**
 * Copies declared static extension assets from source packages into root dist.
 */
export function copyStaticExtensionAssets(params?: Record<string, unknown>): void;
/**
 * Copies static assets into the dist-runtime overlay from source or root dist.
 */
export function copyStaticExtensionAssetsToRuntimeOverlay(params?: Record<string, unknown>): void;
/**
 * Copies declared static assets for one package runtime build.
 */
export function copyStaticExtensionAssetsForPackage(params: unknown): string[];
