/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export interface AuthProfileState {
  state_json: string;
  state_key: string;
  updated_at: number;
}

export interface AuthProfileStore {
  store_json: string;
  store_key: string;
  updated_at: number;
}

export interface CacheEntries {
  blob: Uint8Array | null;
  expires_at: number | null;
  key: string;
  scope: string;
  updated_at: number;
  value_json: string | null;
}

export interface Conversations {
  account_id: string;
  channel: string;
  conversation_id: string;
  created_at: number;
  kind: string;
  label: string | null;
  metadata_json: string | null;
  native_channel_id: string | null;
  native_direct_user_id: string | null;
  parent_conversation_id: string | null;
  peer_id: string;
  thread_id: string | null;
  updated_at: number;
}

export interface MemoryEmbeddingCache {
  dims: number | null;
  embedding: string;
  hash: string;
  model: string;
  provider: string;
  provider_key: string;
  updated_at: number;
}

export interface MemoryIndexChunks {
  embedding: string;
  end_line: number;
  hash: string;
  id: string;
  model: string;
  path: string;
  source: Generated<string>;
  start_line: number;
  text: string;
  updated_at: number;
}

export interface MemoryIndexMeta {
  key: string;
  value: string;
}

export interface MemoryIndexSources {
  hash: string;
  id: Generated<number>;
  mtime: number;
  path: string;
  size: number;
  source: Generated<string>;
}

export interface MemoryIndexState {
  id: Generated<number>;
  revision: number;
}

export interface SchemaMeta {
  agent_id: string | null;
  app_version: string | null;
  created_at: number;
  meta_key: string;
  role: string;
  schema_version: number;
  updated_at: number;
}

export interface SessionConversations {
  conversation_id: string;
  first_seen_at: number;
  last_seen_at: number;
  role: Generated<string>;
  session_id: string;
}

export interface SessionEntries {
  entry_json: string;
  session_id: string;
  session_key: string;
  status: string | null;
  updated_at: number;
}

export interface SessionRoutes {
  session_id: string;
  session_key: string;
  updated_at: number;
}

export interface SessionTranscriptActiveEvents {
  active_position: number;
  event_seq: number;
  message_position: number | null;
  session_id: string;
}

export interface SessionTranscriptFts {
  message_id: string | null;
  role: string | null;
  session_id: string | null;
  text: string | null;
  timestamp: string | null;
}

export interface SessionTranscriptFtsConfig {
  k: string;
  v: string | null;
}

export interface SessionTranscriptFtsContent {
  c0: string | null;
  c1: string | null;
  c2: string | null;
  c3: string | null;
  c4: string | null;
  id: Generated<number>;
}

export interface SessionTranscriptFtsData {
  block: Uint8Array | null;
  id: Generated<number>;
}

export interface SessionTranscriptFtsDocsize {
  id: Generated<number>;
  sz: Uint8Array | null;
}

export interface SessionTranscriptFtsIdx {
  pgno: string | null;
  segid: string;
  term: string;
}

export interface SessionTranscriptIndexState {
  active_event_count: Generated<number>;
  active_message_count: Generated<number>;
  indexed_seq: number;
  leaf_event_id: string | null;
  needs_rebuild: Generated<number>;
  session_id: string;
  updated_at: number;
}

export interface Sessions {
  account_id: string | null;
  acp_owned: Generated<number>;
  agent_harness_id: string | null;
  channel: string | null;
  chat_type: string | null;
  created_at: number;
  display_name: string | null;
  ended_at: number | null;
  hook_external_content_source: string | null;
  model: string | null;
  model_provider: string | null;
  parent_session_key: string | null;
  plugin_owner_id: string | null;
  primary_conversation_id: string | null;
  session_entry_provenance: Generated<number>;
  session_id: string;
  session_key: string;
  session_scope: Generated<string>;
  spawned_by: string | null;
  started_at: number | null;
  status: string | null;
  transcript_observed_at: Generated<number | null>;
  transcript_updated_at: Generated<number | null>;
  updated_at: number;
}

export interface StateLeases {
  created_at: number;
  expires_at: number | null;
  heartbeat_at: number | null;
  lease_key: string;
  owner: string;
  payload_json: string | null;
  scope: string;
  updated_at: number;
}

export interface TrajectoryRuntimeEvents {
  created_at: number;
  event_json: string;
  run_id: string | null;
  seq: number;
  session_id: string;
}

export interface TranscriptEventIdentities {
  created_at: number;
  event_id: string;
  event_type: string | null;
  message_idempotency_key: string | null;
  parent_id: string | null;
  seq: number;
  session_id: string;
}

export interface TranscriptEvents {
  created_at: number;
  event_json: string;
  seq: number;
  session_id: string;
}

export interface DB {
  auth_profile_state: AuthProfileState;
  auth_profile_store: AuthProfileStore;
  cache_entries: CacheEntries;
  conversations: Conversations;
  memory_embedding_cache: MemoryEmbeddingCache;
  memory_index_chunks: MemoryIndexChunks;
  memory_index_meta: MemoryIndexMeta;
  memory_index_sources: MemoryIndexSources;
  memory_index_state: MemoryIndexState;
  schema_meta: SchemaMeta;
  session_conversations: SessionConversations;
  session_entries: SessionEntries;
  session_routes: SessionRoutes;
  session_transcript_active_events: SessionTranscriptActiveEvents;
  session_transcript_fts: SessionTranscriptFts;
  session_transcript_fts_config: SessionTranscriptFtsConfig;
  session_transcript_fts_content: SessionTranscriptFtsContent;
  session_transcript_fts_data: SessionTranscriptFtsData;
  session_transcript_fts_docsize: SessionTranscriptFtsDocsize;
  session_transcript_fts_idx: SessionTranscriptFtsIdx;
  session_transcript_index_state: SessionTranscriptIndexState;
  sessions: Sessions;
  state_leases: StateLeases;
  trajectory_runtime_events: TrajectoryRuntimeEvents;
  transcript_event_identities: TranscriptEventIdentities;
  transcript_events: TranscriptEvents;
}
