import { z } from "zod";
import type { CallMode } from "./config.js";

const ProviderNameSchema = z.enum(["telnyx", "twilio", "plivo", "mock"]);
/** Carrier/provider ids implemented by the voice-call plugin. */
export type ProviderName = z.infer<typeof ProviderNameSchema>;

/** Internal call identifier generated by OpenClaw and used for manager/session state. */
export type CallId = string;

/** Provider-specific call identifier used by carrier webhooks and control APIs. */
type ProviderCallId = string;

const CallStateSchema = z.enum([
  // Non-terminal states
  "initiated",
  "ringing",
  "answered",
  "active",
  "speaking",
  "listening",
  // Terminal states
  "completed",
  "hangup-user",
  "hangup-bot",
  "timeout",
  "error",
  "failed",
  "no-answer",
  "busy",
  "voicemail",
]);
/** Normalized call lifecycle state used by manager persistence and provider events. */
export type CallState = z.infer<typeof CallStateSchema>;

export const TerminalStates = new Set<CallState>([
  "completed",
  "hangup-user",
  "hangup-bot",
  "timeout",
  "error",
  "failed",
  "no-answer",
  "busy",
  "voicemail",
]);

const EndReasonSchema = z.enum([
  "completed",
  "hangup-user",
  "hangup-bot",
  "timeout",
  "error",
  "failed",
  "no-answer",
  "busy",
  "voicemail",
]);
/** Terminal call reason persisted after a provider or local hangup event. */
export type EndReason = z.infer<typeof EndReasonSchema>;

const BaseEventSchema = z.object({
  id: z.string(),
  // Stable provider-derived key for idempotency/replay dedupe.
  dedupeKey: z.string().optional(),
  callId: z.string(),
  providerCallId: z.string().optional(),
  timestamp: z.number(),
  // Optional per-turn nonce for speech events (Twilio <Gather> replay hardening).
  turnToken: z.string().optional(),
  // Optional fields for inbound call detection
  direction: z.enum(["inbound", "outbound"]).optional(),
  from: z.string().optional(),
  to: z.string().optional(),
});

const NormalizedEventSchema = z.discriminatedUnion("type", [
  BaseEventSchema.extend({
    type: z.literal("call.initiated"),
  }),
  BaseEventSchema.extend({
    type: z.literal("call.ringing"),
  }),
  BaseEventSchema.extend({
    type: z.literal("call.answered"),
  }),
  BaseEventSchema.extend({
    type: z.literal("call.active"),
  }),
  BaseEventSchema.extend({
    type: z.literal("call.speaking"),
    text: z.string(),
  }),
  BaseEventSchema.extend({
    type: z.literal("call.speech"),
    transcript: z.string(),
    isFinal: z.boolean(),
    confidence: z.number().min(0).max(1).optional(),
  }),
  BaseEventSchema.extend({
    type: z.literal("call.silence"),
    durationMs: z.number(),
  }),
  BaseEventSchema.extend({
    type: z.literal("call.dtmf"),
    digits: z.string(),
  }),
  BaseEventSchema.extend({
    type: z.literal("call.ended"),
    reason: EndReasonSchema,
  }),
  BaseEventSchema.extend({
    type: z.literal("call.error"),
    error: z.string(),
    retryable: z.boolean().optional(),
  }),
]);
/** Provider webhook events normalized before manager state transitions run. */
export type NormalizedEvent = z.infer<typeof NormalizedEventSchema>;

const CallDirectionSchema = z.enum(["outbound", "inbound"]);

const TranscriptEntrySchema = z.object({
  timestamp: z.number(),
  speaker: z.enum(["bot", "user"]),
  text: z.string(),
  isFinal: z.boolean().default(true),
});
/** Transcript row stored on a call record after speech or bot output events. */
export type TranscriptEntry = z.infer<typeof TranscriptEntrySchema>;

export const CallRecordSchema = z.object({
  /** Internal call id that keys active manager state and persisted snapshots. */
  callId: z.string(),
  /** Provider call id once the carrier has accepted or reported the call. */
  providerCallId: z.string().optional(),
  /** Provider that owns this call record. */
  provider: ProviderNameSchema,
  /** Whether OpenClaw placed the call or received it from the provider webhook. */
  direction: CallDirectionSchema,
  /** Current normalized lifecycle state. */
  state: CallStateSchema,
  /** Caller/source phone number. */
  from: z.string(),
  /** Destination/OpenClaw phone number. */
  to: z.string(),
  /** Persisted agent session key for classic and realtime voice turns. */
  sessionKey: z.string().optional(),
  /** Local or provider event timestamp when the call record was created. */
  startedAt: z.number(),
  /** Provider event timestamp for answer, when known. */
  answeredAt: z.number().optional(),
  /** Provider/local timestamp for terminal state, when known. */
  endedAt: z.number().optional(),
  /** Terminal reason after finalization. */
  endReason: EndReasonSchema.optional(),
  /** User/bot transcript entries retained for response generation and restore. */
  transcript: z.array(TranscriptEntrySchema).default([]),
  /** Provider event replay keys already applied to this call. */
  processedEventIds: z.array(z.string()).default([]),
  /** Route, mode, latency, and provider-specific metadata kept with the call. */
  metadata: z.record(z.string(), z.unknown()).optional(),
});
/** Persisted call state shared by the manager, webhook, and restore flow. */
export type CallRecord = z.infer<typeof CallRecordSchema>;

/** Result of authenticating a provider webhook before event parsing. */
export type WebhookVerificationResult = {
  ok: boolean;
  reason?: string;
  /** Signature is valid, but request was seen before within replay window. */
  isReplay?: boolean;
  /** Stable key derived from authenticated request material. */
  verifiedRequestKey?: string;
};

export type WebhookParseOptions = {
  /** Stable request key from verifyWebhook. */
  verifiedRequestKey?: string;
};

/** Raw HTTP webhook request material passed to provider adapters. */
export type WebhookContext = {
  headers: Record<string, string | string[] | undefined>;
  rawBody: string;
  url: string;
  method: "GET" | "POST" | "PUT" | "DELETE" | "PATCH";
  query?: Record<string, string | string[] | undefined>;
  remoteAddress?: string;
};

/** Provider adapter output after converting one webhook request into normalized events. */
export type ProviderWebhookParseResult = {
  /** Normalized provider events to apply in manager order. */
  events: NormalizedEvent[];
  /** Optional immediate response body, such as TwiML/XML expected by the carrier. */
  providerResponseBody?: string;
  /** Headers for the immediate carrier response. */
  providerResponseHeaders?: Record<string, string>;
  /** HTTP status for the immediate carrier response; defaults at the webhook layer. */
  statusCode?: number;
};

/** Request shape for starting an outbound provider call. */
export type InitiateCallInput = {
  callId: CallId;
  from: string;
  to: string;
  webhookUrl: string;
  clientState?: Record<string, string>;
  /** Inline TwiML to execute without fetching webhook TwiML. */
  inlineTwiml?: string;
  /** TwiML to serve once before normal webhook-driven call handling resumes. */
  preConnectTwiml?: string;
  /**
   * Optional `wss://` URL the carrier should open for bidirectional Media
   * Streaming on call connect. Used by carriers (e.g. Telnyx) that attach
   * streaming at dial time. Twilio learns the URL from TwiML so it ignores
   * this field.
   */
  streamUrl?: string;
  /** Per-call auth token the carrier echoes back on the WS upgrade. */
  streamAuthToken?: string;
};

export type InitiateCallResult = {
  /** Provider call id that subsequent webhooks/control calls will reference. */
  providerCallId: ProviderCallId;
  /** Provider acceptance state after outbound dial request creation. */
  status: "initiated" | "queued";
};

/** Request shape for ending an active provider call. */
export type HangupCallInput = {
  callId: CallId;
  providerCallId: ProviderCallId;
  reason: EndReason;
};

/** Request shape for provider APIs that answer inbound calls explicitly. */
export type AnswerCallInput = {
  callId: CallId;
  providerCallId: ProviderCallId;
  /**
   * Optional `wss://` URL the carrier should open for bidirectional Media
   * Streaming on answer. Used by carriers (e.g. Telnyx) that attach
   * streaming at answer time. Twilio learns the URL from TwiML so it ignores
   * this field.
   */
  streamUrl?: string;
  /** Per-call auth token the carrier echoes back on the WS upgrade. */
  streamAuthToken?: string;
};

/** Provider TTS request for speaking text into an active call. */
export type PlayTtsInput = {
  callId: CallId;
  providerCallId: ProviderCallId;
  text: string;
  voice?: string;
  locale?: string;
};

/** Provider DTMF request for an active call. */
export type SendDtmfInput = {
  callId: CallId;
  providerCallId: ProviderCallId;
  digits: string;
};

/** Provider STT/listening request for an active call turn. */
export type StartListeningInput = {
  callId: CallId;
  providerCallId: ProviderCallId;
  language?: string;
  /** Optional per-turn nonce for provider callbacks (replay hardening). */
  turnToken?: string;
};

/** Provider request to stop collecting user speech. */
export type StopListeningInput = {
  /** Internal call id for logs and manager correlation. */
  callId: CallId;
  /** Provider call id for the active call leg. */
  providerCallId: ProviderCallId;
};

/** Provider lookup request used when restoring persisted calls after restart. */
export type GetCallStatusInput = {
  /** Provider call id to reconcile after restore. */
  providerCallId: ProviderCallId;
};

/** Provider status lookup result used to decide whether restored calls stay active. */
export type GetCallStatusResult = {
  /** Provider-specific status string (e.g. "completed", "in-progress") */
  status: string;
  /** True when the provider confirms the call has ended */
  isTerminal: boolean;
  /** True when the status could not be determined (transient error) */
  isUnknown?: boolean;
};

/** User-facing outbound call options accepted by voice-call tools. */
export type OutboundCallOptions = {
  /** Message to speak when call connects. */
  message?: string;
  /** Call mode override for this outbound call. */
  mode?: CallMode;
  /** DTMF digits to execute before conversation webhook control resumes. */
  dtmfSequence?: string;
  /** Session that initiated the call, used for forked realtime consult context. */
  requesterSessionKey?: string;
};
