// Generated by scripts/generate-plugin-sdk-facades.mjs. Do not edit manually.
export {
  ANTHROPIC_VERTEX_DEFAULT_MODEL_ID,
  buildAnthropicVertexProvider,
  resolveAnthropicVertexRegion,
} from "../../extensions/anthropic-vertex/api.js";
