// Generated by scripts/generate-plugin-sdk-facades.mjs. Do not edit manually.
export {
  buildDiscordComponentMessage,
  collectDiscordStatusIssues,
  createDiscordActionGate,
  handleDiscordMessageAction,
  inspectDiscordAccount,
  listDiscordAccountIds,
  listDiscordDirectoryGroupsFromConfig,
  listDiscordDirectoryPeersFromConfig,
  looksLikeDiscordTargetId,
  normalizeDiscordMessagingTarget,
  normalizeDiscordOutboundTarget,
  readDiscordComponentSpec,
  resolveDefaultDiscordAccountId,
  resolveDiscordAccount,
  resolveDiscordChannelId,
  resolveDiscordGroupRequireMention,
  resolveDiscordGroupToolPolicy,
} from "../../extensions/discord/api.js";
export type {
  DiscordComponentMessageSpec,
  DiscordSendComponents,
  DiscordSendEmbeds,
  DiscordSendResult,
  InspectedDiscordAccount,
  ResolvedDiscordAccount,
} from "../../extensions/discord/api.js";
