import {
  listDiscordDirectoryGroupsFromConfig,
  listDiscordDirectoryPeersFromConfig,
} from "../../extensions/discord/api.js";
import type {
  ThreadBindingManager,
  ThreadBindingRecord,
  ThreadBindingTargetKind,
} from "../../extensions/discord/runtime-api.js";
import {
  autoBindSpawnedDiscordSubagent,
  getThreadBindingManager,
  listDiscordDirectoryGroupsLive,
  listDiscordDirectoryPeersLive,
  listThreadBindingsBySessionKey,
  resolveDiscordChannelAllowlist,
  resolveDiscordUserAllowlist,
  resolveThreadBindingIdleTimeoutMs,
  resolveThreadBindingInactivityExpiresAt,
  resolveThreadBindingMaxAgeExpiresAt,
  resolveThreadBindingMaxAgeMs,
  setThreadBindingIdleTimeoutBySessionKey,
  setThreadBindingMaxAgeBySessionKey,
  unbindThreadBindingsBySessionKey,
} from "../../extensions/discord/runtime-api.js";
import { normalizeExplicitDiscordSessionKey } from "../../extensions/discord/session-key-api.js";
import type {
  DiscordPluralKitConfig,
  DiscordSendComponents,
  DiscordSendEmbeds,
  InspectedDiscordAccount,
  ResolvedDiscordAccount,
} from "../channels/discord/plugin-sdk-bridge.js";
import {
  collectDiscordStatusIssues,
  createDiscordActionGate,
  inspectDiscordAccount,
  listDiscordAccountIds,
  looksLikeDiscordTargetId,
  normalizeDiscordMessagingTarget,
  normalizeDiscordOutboundTarget,
  readDiscordComponentSpec,
  resolveDefaultDiscordAccountId,
  resolveDiscordChannelId,
  resolveDiscordGroupRequireMention,
  resolveDiscordGroupToolPolicy,
} from "../channels/discord/plugin-sdk-bridge.js";
import {
  addRoleDiscord,
  auditDiscordChannelPermissions,
  banMemberDiscord,
  collectDiscordAuditChannelIds,
  createChannelDiscord,
  createScheduledEventDiscord,
  createThreadDiscord,
  deleteChannelDiscord,
  deleteMessageDiscord,
  DISCORD_DEFAULT_INBOUND_WORKER_TIMEOUT_MS,
  DISCORD_DEFAULT_LISTENER_TIMEOUT_MS,
  discordMessageActions,
  editChannelDiscord,
  editMessageDiscord,
  fetchChannelInfoDiscord,
  fetchChannelPermissionsDiscord,
  fetchMemberInfoDiscord,
  fetchMessageDiscord,
  fetchReactionsDiscord,
  fetchRoleInfoDiscord,
  fetchVoiceStatusDiscord,
  getGateway,
  getPresence,
  hasAnyGuildPermissionDiscord,
  kickMemberDiscord,
  listGuildChannelsDiscord,
  listGuildEmojisDiscord,
  listPinsDiscord,
  listScheduledEventsDiscord,
  listThreadsDiscord,
  monitorDiscordProvider,
  moveChannelDiscord,
  pinMessageDiscord,
  probeDiscord,
  reactMessageDiscord,
  readMessagesDiscord,
  removeChannelPermissionDiscord,
  removeOwnReactionsDiscord,
  removeReactionDiscord,
  removeRoleDiscord,
  searchMessagesDiscord,
  sendDiscordComponentMessage,
  sendMessageDiscord,
  sendPollDiscord,
  sendStickerDiscord,
  sendTypingDiscord,
  sendVoiceMessageDiscord,
  setChannelPermissionDiscord,
  timeoutMemberDiscord,
  unpinMessageDiscord,
  uploadEmojiDiscord,
  uploadStickerDiscord,
} from "../channels/discord/plugin-sdk-bridge.js";

export type {
  ChannelAccountSnapshot,
  ChannelGatewayContext,
  ChannelMessageActionAdapter,
} from "../channels/plugins/types.js";
export type { OpenClawConfig } from "../config/config.js";
export type { DiscordAccountConfig, DiscordActionConfig } from "../config/types.js";
export type { DiscordConfig } from "../config/types.discord.js";
export type {
  DiscordPluralKitConfig,
  DiscordSendComponents,
  DiscordSendEmbeds,
  InspectedDiscordAccount,
  ResolvedDiscordAccount,
  ThreadBindingManager,
  ThreadBindingRecord,
  ThreadBindingTargetKind,
};
export type {
  ChannelConfiguredBindingProvider,
  ChannelConfiguredBindingConversationRef,
  ChannelConfiguredBindingMatch,
} from "../channels/plugins/types.adapters.js";
export type {
  ChannelMessageActionContext,
  ChannelPlugin,
  OpenClawPluginApi,
  PluginRuntime,
} from "./channel-plugin-common.js";
export {
  DEFAULT_ACCOUNT_ID,
  PAIRING_APPROVED_MESSAGE,
  applyAccountNameToChannelSection,
  buildChannelConfigSchema,
  deleteAccountFromConfigSection,
  emptyPluginConfigSchema,
  formatPairingApproveHint,
  getChatChannelMeta,
  migrateBaseNameToDefaultAccount,
  normalizeAccountId,
  setAccountEnabledInConfigSection,
} from "./channel-plugin-common.js";
export { formatDocsLink } from "../terminal/links.js";

export {
  projectCredentialSnapshotFields,
  resolveConfiguredFromCredentialStatuses,
} from "../channels/account-snapshot-fields.js";
export {
  resolveDefaultGroupPolicy,
  resolveOpenProviderRuntimeGroupPolicy,
} from "../config/runtime-group-policy.js";
export { listDiscordDirectoryGroupsFromConfig, listDiscordDirectoryPeersFromConfig };
export { resolveDiscordGroupRequireMention, resolveDiscordGroupToolPolicy };
export { DiscordConfigSchema } from "../config/zod-schema.providers-core.js";

export {
  buildComputedAccountStatusSnapshot,
  buildTokenChannelStatusSummary,
} from "./status-helpers.js";

export {
  addRoleDiscord,
  auditDiscordChannelPermissions,
  autoBindSpawnedDiscordSubagent,
  banMemberDiscord,
  collectDiscordAuditChannelIds,
  collectDiscordStatusIssues,
  createChannelDiscord,
  createDiscordActionGate,
  createScheduledEventDiscord,
  createThreadDiscord,
  deleteChannelDiscord,
  deleteMessageDiscord,
  DISCORD_DEFAULT_INBOUND_WORKER_TIMEOUT_MS,
  DISCORD_DEFAULT_LISTENER_TIMEOUT_MS,
  discordMessageActions,
  editChannelDiscord,
  editMessageDiscord,
  fetchChannelInfoDiscord,
  fetchChannelPermissionsDiscord,
  fetchMemberInfoDiscord,
  fetchMessageDiscord,
  fetchReactionsDiscord,
  fetchRoleInfoDiscord,
  fetchVoiceStatusDiscord,
  getGateway,
  getPresence,
  getThreadBindingManager,
  hasAnyGuildPermissionDiscord,
  inspectDiscordAccount,
  kickMemberDiscord,
  listDiscordAccountIds,
  listDiscordDirectoryGroupsLive,
  listDiscordDirectoryPeersLive,
  listGuildChannelsDiscord,
  listGuildEmojisDiscord,
  listPinsDiscord,
  listScheduledEventsDiscord,
  listThreadBindingsBySessionKey,
  listThreadsDiscord,
  looksLikeDiscordTargetId,
  monitorDiscordProvider,
  moveChannelDiscord,
  normalizeDiscordMessagingTarget,
  normalizeDiscordOutboundTarget,
  normalizeExplicitDiscordSessionKey,
  pinMessageDiscord,
  probeDiscord,
  reactMessageDiscord,
  readDiscordComponentSpec,
  readMessagesDiscord,
  removeChannelPermissionDiscord,
  removeOwnReactionsDiscord,
  removeReactionDiscord,
  removeRoleDiscord,
  resolveDefaultDiscordAccountId,
  resolveDiscordChannelAllowlist,
  resolveDiscordChannelId,
  resolveDiscordUserAllowlist,
  resolveThreadBindingIdleTimeoutMs,
  resolveThreadBindingInactivityExpiresAt,
  resolveThreadBindingMaxAgeExpiresAt,
  resolveThreadBindingMaxAgeMs,
  searchMessagesDiscord,
  sendDiscordComponentMessage,
  sendMessageDiscord,
  sendPollDiscord,
  sendStickerDiscord,
  sendTypingDiscord,
  sendVoiceMessageDiscord,
  setChannelPermissionDiscord,
  setThreadBindingIdleTimeoutBySessionKey,
  setThreadBindingMaxAgeBySessionKey,
  timeoutMemberDiscord,
  unbindThreadBindingsBySessionKey,
  unpinMessageDiscord,
  uploadEmojiDiscord,
  uploadStickerDiscord,
};
