// Generated by scripts/generate-plugin-sdk-facades.mjs. Do not edit manually.
export {
  applyGoogleGeminiModelDefault,
  createGoogleThinkingPayloadWrapper,
  DEFAULT_GOOGLE_API_BASE_URL,
  GOOGLE_GEMINI_DEFAULT_MODEL,
  normalizeGoogleApiBaseUrl,
  normalizeGoogleModelId,
  parseGeminiAuth,
  sanitizeGoogleThinkingPayload,
} from "../../extensions/google/api.js";
