// Generated by scripts/generate-plugin-sdk-facades.mjs. Do not edit manually.
import type { PluginSdkFacadeTypeMap } from "../generated/plugin-sdk-facade-type-map.generated.js";
type FacadeEntry = PluginSdkFacadeTypeMap["imessage-targets"];
type FacadeModule = FacadeEntry["module"];
import { loadBundledPluginPublicSurfaceModuleSync } from "./facade-runtime.js";

function loadFacadeModule(): FacadeModule {
  return loadBundledPluginPublicSurfaceModuleSync<FacadeModule>({
    dirName: "imessage",
    artifactBasename: "api.js",
  });
}
export const normalizeIMessageHandle: FacadeModule["normalizeIMessageHandle"] = ((...args) =>
  loadFacadeModule()["normalizeIMessageHandle"](
    ...args,
  )) as FacadeModule["normalizeIMessageHandle"];
export const parseChatAllowTargetPrefixes: FacadeModule["parseChatAllowTargetPrefixes"] = ((
  ...args
) =>
  loadFacadeModule()["parseChatAllowTargetPrefixes"](
    ...args,
  )) as FacadeModule["parseChatAllowTargetPrefixes"];
export const parseChatTargetPrefixesOrThrow: FacadeModule["parseChatTargetPrefixesOrThrow"] = ((
  ...args
) =>
  loadFacadeModule()["parseChatTargetPrefixesOrThrow"](
    ...args,
  )) as FacadeModule["parseChatTargetPrefixesOrThrow"];
export const resolveServicePrefixedAllowTarget: FacadeModule["resolveServicePrefixedAllowTarget"] =
  ((...args) =>
    loadFacadeModule()["resolveServicePrefixedAllowTarget"](
      ...args,
    )) as FacadeModule["resolveServicePrefixedAllowTarget"];
export const resolveServicePrefixedTarget: FacadeModule["resolveServicePrefixedTarget"] = ((
  ...args
) =>
  loadFacadeModule()["resolveServicePrefixedTarget"](
    ...args,
  )) as FacadeModule["resolveServicePrefixedTarget"];
export type ParsedChatTarget = FacadeEntry["types"]["ParsedChatTarget"];
