// Generated by scripts/generate-plugin-sdk-facades.mjs. Do not edit manually.
import type { PluginSdkFacadeTypeMap } from "../generated/plugin-sdk-facade-type-map.generated.js";
type FacadeEntry = PluginSdkFacadeTypeMap["imessage-runtime"];
type FacadeModule = FacadeEntry["module"];
import { loadBundledPluginPublicSurfaceModuleSync } from "./facade-runtime.js";

function loadFacadeModule(): FacadeModule {
  return loadBundledPluginPublicSurfaceModuleSync<FacadeModule>({
    dirName: "imessage",
    artifactBasename: "runtime-api.js",
  });
}
export const monitorIMessageProvider: FacadeModule["monitorIMessageProvider"] = ((...args) =>
  loadFacadeModule()["monitorIMessageProvider"](
    ...args,
  )) as FacadeModule["monitorIMessageProvider"];
export const probeIMessage: FacadeModule["probeIMessage"] = ((...args) =>
  loadFacadeModule()["probeIMessage"](...args)) as FacadeModule["probeIMessage"];
export const sendMessageIMessage: FacadeModule["sendMessageIMessage"] = ((...args) =>
  loadFacadeModule()["sendMessageIMessage"](...args)) as FacadeModule["sendMessageIMessage"];
export type IMessageProbe = FacadeEntry["types"]["IMessageProbe"];
