// Generated by scripts/generate-plugin-sdk-facades.mjs. Do not edit manually.
import type { PluginSdkFacadeTypeMap } from "../generated/plugin-sdk-facade-type-map.generated.js";
type FacadeEntry = PluginSdkFacadeTypeMap["imessage-policy"];
type FacadeModule = FacadeEntry["module"];
import { loadBundledPluginPublicSurfaceModuleSync } from "./facade-runtime.js";

function loadFacadeModule(): FacadeModule {
  return loadBundledPluginPublicSurfaceModuleSync<FacadeModule>({
    dirName: "imessage",
    artifactBasename: "api.js",
  });
}
export const normalizeIMessageHandle: FacadeModule["normalizeIMessageHandle"] = ((...args) =>
  loadFacadeModule()["normalizeIMessageHandle"](
    ...args,
  )) as FacadeModule["normalizeIMessageHandle"];
export const resolveIMessageRuntimeGroupPolicy: FacadeModule["resolveIMessageRuntimeGroupPolicy"] =
  ((...args) =>
    loadFacadeModule()["resolveIMessageRuntimeGroupPolicy"](
      ...args,
    )) as FacadeModule["resolveIMessageRuntimeGroupPolicy"];
export const resolveIMessageGroupRequireMention: FacadeModule["resolveIMessageGroupRequireMention"] =
  ((...args) =>
    loadFacadeModule()["resolveIMessageGroupRequireMention"](
      ...args,
    )) as FacadeModule["resolveIMessageGroupRequireMention"];
export const resolveIMessageGroupToolPolicy: FacadeModule["resolveIMessageGroupToolPolicy"] = ((
  ...args
) =>
  loadFacadeModule()["resolveIMessageGroupToolPolicy"](
    ...args,
  )) as FacadeModule["resolveIMessageGroupToolPolicy"];
