// Generated by scripts/generate-plugin-sdk-facades.mjs. Do not edit manually.
export {
  createMatrixThreadBindingManager,
  resetMatrixThreadBindingsForTests,
} from "../../extensions/matrix/api.js";
