// Generated by scripts/generate-plugin-sdk-facades.mjs. Do not edit manually.
export {
  buildMinimaxPortalProvider,
  buildMinimaxProvider,
  isMiniMaxModernModelId,
  MINIMAX_DEFAULT_MODEL_ID,
  MINIMAX_DEFAULT_MODEL_REF,
  MINIMAX_TEXT_MODEL_CATALOG,
  MINIMAX_TEXT_MODEL_ORDER,
  MINIMAX_TEXT_MODEL_REFS,
} from "../../extensions/minimax/api.js";
