// Generated by scripts/generate-plugin-sdk-facades.mjs. Do not edit manually.
export {
  applyMistralConfig,
  applyMistralProviderConfig,
  buildMistralModelDefinition,
  buildMistralProvider,
  MISTRAL_BASE_URL,
  MISTRAL_DEFAULT_MODEL_ID,
  MISTRAL_DEFAULT_MODEL_REF,
} from "../../extensions/mistral/api.js";
