// Generated by scripts/generate-plugin-sdk-facades.mjs. Do not edit manually.
export {
  MODELSTUDIO_BASE_URL,
  MODELSTUDIO_DEFAULT_MODEL_ID,
  buildModelStudioProvider,
} from "../../extensions/modelstudio/api.js";
