// Generated by scripts/generate-plugin-sdk-facades.mjs. Do not edit manually.
export {
  applyOpenrouterConfig,
  applyOpenrouterProviderConfig,
  buildOpenrouterProvider,
  OPENROUTER_DEFAULT_MODEL_REF,
} from "../../extensions/openrouter/api.js";
