// Generated by scripts/generate-plugin-sdk-facades.mjs. Do not edit manually.
import type { PluginSdkFacadeTypeMap } from "../generated/plugin-sdk-facade-type-map.generated.js";
type FacadeEntry = PluginSdkFacadeTypeMap["qwen"];
type FacadeModule = FacadeEntry["module"];
import {
  createLazyFacadeArrayValue,
  createLazyFacadeObjectValue,
  loadBundledPluginPublicSurfaceModuleSync,
} from "./facade-runtime.js";

function loadFacadeModule(): FacadeModule {
  return loadBundledPluginPublicSurfaceModuleSync<FacadeModule>({
    dirName: "qwen",
    artifactBasename: "api.js",
  });
}
export const applyQwenNativeStreamingUsageCompat: FacadeModule["applyQwenNativeStreamingUsageCompat"] =
  ((...args) =>
    loadFacadeModule()["applyQwenNativeStreamingUsageCompat"](
      ...args,
    )) as FacadeModule["applyQwenNativeStreamingUsageCompat"];
export const buildQwenDefaultModelDefinition: FacadeModule["buildQwenDefaultModelDefinition"] = ((
  ...args
) =>
  loadFacadeModule()["buildQwenDefaultModelDefinition"](
    ...args,
  )) as FacadeModule["buildQwenDefaultModelDefinition"];
export const buildQwenModelDefinition: FacadeModule["buildQwenModelDefinition"] = ((...args) =>
  loadFacadeModule()["buildQwenModelDefinition"](
    ...args,
  )) as FacadeModule["buildQwenModelDefinition"];
export const QWEN_BASE_URL: FacadeModule["QWEN_BASE_URL"] = loadFacadeModule()["QWEN_BASE_URL"];
export const QWEN_CN_BASE_URL: FacadeModule["QWEN_CN_BASE_URL"] =
  loadFacadeModule()["QWEN_CN_BASE_URL"];
export const QWEN_DEFAULT_COST: FacadeModule["QWEN_DEFAULT_COST"] = createLazyFacadeObjectValue(
  () => loadFacadeModule()["QWEN_DEFAULT_COST"] as object,
) as FacadeModule["QWEN_DEFAULT_COST"];
export const QWEN_DEFAULT_MODEL_ID: FacadeModule["QWEN_DEFAULT_MODEL_ID"] =
  loadFacadeModule()["QWEN_DEFAULT_MODEL_ID"];
export const QWEN_DEFAULT_MODEL_REF: FacadeModule["QWEN_DEFAULT_MODEL_REF"] =
  loadFacadeModule()["QWEN_DEFAULT_MODEL_REF"];
export const QWEN_GLOBAL_BASE_URL: FacadeModule["QWEN_GLOBAL_BASE_URL"] =
  loadFacadeModule()["QWEN_GLOBAL_BASE_URL"];
export const QWEN_STANDARD_CN_BASE_URL: FacadeModule["QWEN_STANDARD_CN_BASE_URL"] =
  loadFacadeModule()["QWEN_STANDARD_CN_BASE_URL"];
export const QWEN_STANDARD_GLOBAL_BASE_URL: FacadeModule["QWEN_STANDARD_GLOBAL_BASE_URL"] =
  loadFacadeModule()["QWEN_STANDARD_GLOBAL_BASE_URL"];
export const QWEN_MODEL_CATALOG: FacadeModule["QWEN_MODEL_CATALOG"] = createLazyFacadeArrayValue(
  () => loadFacadeModule()["QWEN_MODEL_CATALOG"] as unknown as readonly unknown[],
) as FacadeModule["QWEN_MODEL_CATALOG"];
export const isNativeQwenBaseUrl: FacadeModule["isNativeQwenBaseUrl"] = ((...args) =>
  loadFacadeModule()["isNativeQwenBaseUrl"](...args)) as FacadeModule["isNativeQwenBaseUrl"];
export const buildQwenProvider: FacadeModule["buildQwenProvider"] = ((...args) =>
  loadFacadeModule()["buildQwenProvider"](...args)) as FacadeModule["buildQwenProvider"];
