// Generated by scripts/generate-plugin-sdk-facades.mjs. Do not edit manually.
import type { PluginSdkFacadeTypeMap } from "../generated/plugin-sdk-facade-type-map.generated.js";
type FacadeEntry = PluginSdkFacadeTypeMap["telegram-runtime-surface"];
type FacadeModule = FacadeEntry["module"];
import {
  createLazyFacadeObjectValue,
  loadBundledPluginPublicSurfaceModuleSync,
} from "./facade-runtime.js";

function loadFacadeModule(): FacadeModule {
  return loadBundledPluginPublicSurfaceModuleSync<FacadeModule>({
    dirName: "telegram",
    artifactBasename: "runtime-api.js",
  });
}
export const auditTelegramGroupMembership: FacadeModule["auditTelegramGroupMembership"] = ((
  ...args
) =>
  loadFacadeModule()["auditTelegramGroupMembership"](
    ...args,
  )) as FacadeModule["auditTelegramGroupMembership"];
export const buildTelegramExecApprovalPendingPayload: FacadeModule["buildTelegramExecApprovalPendingPayload"] =
  ((...args) =>
    loadFacadeModule()["buildTelegramExecApprovalPendingPayload"](
      ...args,
    )) as FacadeModule["buildTelegramExecApprovalPendingPayload"];
export const collectTelegramUnmentionedGroupIds: FacadeModule["collectTelegramUnmentionedGroupIds"] =
  ((...args) =>
    loadFacadeModule()["collectTelegramUnmentionedGroupIds"](
      ...args,
    )) as FacadeModule["collectTelegramUnmentionedGroupIds"];
export const createTelegramThreadBindingManager: FacadeModule["createTelegramThreadBindingManager"] =
  ((...args) =>
    loadFacadeModule()["createTelegramThreadBindingManager"](
      ...args,
    )) as FacadeModule["createTelegramThreadBindingManager"];
export const createForumTopicTelegram: FacadeModule["createForumTopicTelegram"] = ((...args) =>
  loadFacadeModule()["createForumTopicTelegram"](
    ...args,
  )) as FacadeModule["createForumTopicTelegram"];
export const deleteMessageTelegram: FacadeModule["deleteMessageTelegram"] = ((...args) =>
  loadFacadeModule()["deleteMessageTelegram"](...args)) as FacadeModule["deleteMessageTelegram"];
export const editForumTopicTelegram: FacadeModule["editForumTopicTelegram"] = ((...args) =>
  loadFacadeModule()["editForumTopicTelegram"](...args)) as FacadeModule["editForumTopicTelegram"];
export const editMessageReplyMarkupTelegram: FacadeModule["editMessageReplyMarkupTelegram"] = ((
  ...args
) =>
  loadFacadeModule()["editMessageReplyMarkupTelegram"](
    ...args,
  )) as FacadeModule["editMessageReplyMarkupTelegram"];
export const editMessageTelegram: FacadeModule["editMessageTelegram"] = ((...args) =>
  loadFacadeModule()["editMessageTelegram"](...args)) as FacadeModule["editMessageTelegram"];
export const monitorTelegramProvider: FacadeModule["monitorTelegramProvider"] = ((...args) =>
  loadFacadeModule()["monitorTelegramProvider"](
    ...args,
  )) as FacadeModule["monitorTelegramProvider"];
export const pinMessageTelegram: FacadeModule["pinMessageTelegram"] = ((...args) =>
  loadFacadeModule()["pinMessageTelegram"](...args)) as FacadeModule["pinMessageTelegram"];
export const probeTelegram: FacadeModule["probeTelegram"] = ((...args) =>
  loadFacadeModule()["probeTelegram"](...args)) as FacadeModule["probeTelegram"];
export const reactMessageTelegram: FacadeModule["reactMessageTelegram"] = ((...args) =>
  loadFacadeModule()["reactMessageTelegram"](...args)) as FacadeModule["reactMessageTelegram"];
export const renameForumTopicTelegram: FacadeModule["renameForumTopicTelegram"] = ((...args) =>
  loadFacadeModule()["renameForumTopicTelegram"](
    ...args,
  )) as FacadeModule["renameForumTopicTelegram"];
export const resetTelegramThreadBindingsForTests: FacadeModule["resetTelegramThreadBindingsForTests"] =
  ((...args) =>
    loadFacadeModule()["resetTelegramThreadBindingsForTests"](
      ...args,
    )) as FacadeModule["resetTelegramThreadBindingsForTests"];
export const resolveTelegramRuntimeGroupPolicy: FacadeModule["resolveTelegramRuntimeGroupPolicy"] =
  ((...args) =>
    loadFacadeModule()["resolveTelegramRuntimeGroupPolicy"](
      ...args,
    )) as FacadeModule["resolveTelegramRuntimeGroupPolicy"];
export const resolveTelegramToken: FacadeModule["resolveTelegramToken"] = ((...args) =>
  loadFacadeModule()["resolveTelegramToken"](...args)) as FacadeModule["resolveTelegramToken"];
export const sendMessageTelegram: FacadeModule["sendMessageTelegram"] = ((...args) =>
  loadFacadeModule()["sendMessageTelegram"](...args)) as FacadeModule["sendMessageTelegram"];
export const sendPollTelegram: FacadeModule["sendPollTelegram"] = ((...args) =>
  loadFacadeModule()["sendPollTelegram"](...args)) as FacadeModule["sendPollTelegram"];
export const sendStickerTelegram: FacadeModule["sendStickerTelegram"] = ((...args) =>
  loadFacadeModule()["sendStickerTelegram"](...args)) as FacadeModule["sendStickerTelegram"];
export const sendTypingTelegram: FacadeModule["sendTypingTelegram"] = ((...args) =>
  loadFacadeModule()["sendTypingTelegram"](...args)) as FacadeModule["sendTypingTelegram"];
export const setTelegramThreadBindingIdleTimeoutBySessionKey: FacadeModule["setTelegramThreadBindingIdleTimeoutBySessionKey"] =
  ((...args) =>
    loadFacadeModule()["setTelegramThreadBindingIdleTimeoutBySessionKey"](
      ...args,
    )) as FacadeModule["setTelegramThreadBindingIdleTimeoutBySessionKey"];
export const setTelegramThreadBindingMaxAgeBySessionKey: FacadeModule["setTelegramThreadBindingMaxAgeBySessionKey"] =
  ((...args) =>
    loadFacadeModule()["setTelegramThreadBindingMaxAgeBySessionKey"](
      ...args,
    )) as FacadeModule["setTelegramThreadBindingMaxAgeBySessionKey"];
export const shouldSuppressTelegramExecApprovalForwardingFallback: FacadeModule["shouldSuppressTelegramExecApprovalForwardingFallback"] =
  ((...args) =>
    loadFacadeModule()["shouldSuppressTelegramExecApprovalForwardingFallback"](
      ...args,
    )) as FacadeModule["shouldSuppressTelegramExecApprovalForwardingFallback"];
export const telegramMessageActions: FacadeModule["telegramMessageActions"] =
  createLazyFacadeObjectValue(
    () => loadFacadeModule()["telegramMessageActions"] as object,
  ) as FacadeModule["telegramMessageActions"];
export const unpinMessageTelegram: FacadeModule["unpinMessageTelegram"] = ((...args) =>
  loadFacadeModule()["unpinMessageTelegram"](...args)) as FacadeModule["unpinMessageTelegram"];
export type TelegramApiOverride = FacadeEntry["types"]["TelegramApiOverride"];
export type TelegramProbe = FacadeEntry["types"]["TelegramProbe"];
