// Generated by scripts/generate-plugin-sdk-facades.mjs. Do not edit manually.
export {
  buildVercelAiGatewayProvider,
  discoverVercelAiGatewayModels,
  getStaticVercelAiGatewayModelCatalog,
  VERCEL_AI_GATEWAY_BASE_URL,
  VERCEL_AI_GATEWAY_DEFAULT_MODEL_REF,
} from "../../extensions/vercel-ai-gateway/api.js";
