// Generated by scripts/generate-plugin-sdk-facades.mjs. Do not edit manually.
import type { PluginSdkFacadeTypeMap } from "../generated/plugin-sdk-facade-type-map.generated.js";
type FacadeEntry = PluginSdkFacadeTypeMap["video-generation-runtime"];
type FacadeModule = FacadeEntry["module"];
import { loadActivatedBundledPluginPublicSurfaceModuleSync } from "./facade-runtime.js";

function loadFacadeModule(): FacadeModule {
  return loadActivatedBundledPluginPublicSurfaceModuleSync<FacadeModule>({
    dirName: "video-generation-core",
    artifactBasename: "runtime-api.js",
  });
}
export const generateVideo: FacadeModule["generateVideo"] = ((...args) =>
  loadFacadeModule()["generateVideo"](...args)) as FacadeModule["generateVideo"];
export const listRuntimeVideoGenerationProviders: FacadeModule["listRuntimeVideoGenerationProviders"] =
  ((...args) =>
    loadFacadeModule()["listRuntimeVideoGenerationProviders"](
      ...args,
    )) as FacadeModule["listRuntimeVideoGenerationProviders"];
export type GenerateVideoParams = FacadeEntry["types"]["GenerateVideoParams"];
export type GenerateVideoRuntimeResult = FacadeEntry["types"]["GenerateVideoRuntimeResult"];
