// Generated by scripts/generate-plugin-sdk-facades.mjs. Do not edit manually.
export {
  isWhatsAppGroupJid,
  isWhatsAppUserTarget,
  normalizeWhatsAppTarget,
} from "./whatsapp-targets-shared.js";
