// Narrow session/runtime facade re-exported for memory transcript helpers.

export {
  canonicalizeMainSessionAlias,
  clearConfigCache,
  clearRuntimeConfigSnapshot,
  getRuntimeConfig,
  HEARTBEAT_PROMPT,
  HEARTBEAT_TOKEN,
  SILENT_REPLY_TOKEN,
  hasInterSessionUserProvenance,
  isCompactionCheckpointTranscriptFileName,
  isCronRunSessionKey,
  isExecCompletionEvent,
  isHeartbeatUserMessage,
  isSessionArchiveArtifactName,
  isSilentReplyPayloadText,
  isUsageCountedSessionTranscriptFileName,
  listSessionEntries,
  onSessionTranscriptUpdate,
  parseUsageCountedSessionIdFromFileName,
  resolveSessionEntryChatType,
  resolveSessionFilePath,
  resolveStorePath,
  resolveSessionAgentId,
  resolveSessionTranscriptsDirForAgent,
  shouldIncludeLongTermMemoryByDefault,
  stripInboundMetadata,
  stripInternalRuntimeContext,
  type SessionEntry,
} from "./openclaw-runtime.js";
