/**
 * Canonical message action names accepted by channel message tool dispatch.
 */
export const CHANNEL_MESSAGE_ACTION_NAMES = [
  "send",
  "broadcast",
  "poll",
  "poll-vote",
  "react",
  "reactions",
  "read",
  "edit",
  "unsend",
  "reply",
  "sendWithEffect",
  "renameGroup",
  "setGroupIcon",
  "addParticipant",
  "removeParticipant",
  "leaveGroup",
  "sendAttachment",
  "delete",
  "pin",
  "unpin",
  "list-pins",
  "permissions",
  "thread-create",
  "thread-list",
  "thread-reply",
  "search",
  "sticker",
  "sticker-search",
  "member-info",
  "role-info",
  "emoji-list",
  "emoji-upload",
  "sticker-upload",
  "role-add",
  "role-remove",
  "channel-info",
  "channel-list",
  "channel-create",
  "channel-edit",
  "channel-delete",
  "channel-move",
  "category-create",
  "category-edit",
  "category-delete",
  "topic-create",
  "topic-edit",
  "voice-status",
  "event-list",
  "event-create",
  "timeout",
  "kick",
  "ban",
  "set-profile",
  "set-presence",
  "download-file",
  "upload-file",
] as const;

/**
 * Message action name union derived from the canonical action list.
 */
export type ChannelMessageActionName = (typeof CHANNEL_MESSAGE_ACTION_NAMES)[number];
