/**
 * Public channel plugin type barrel.
 *
 * Re-exports stable plugin-facing channel types and message action names.
 */
import type { ChannelMessageActionName as ChannelMessageActionNameFromList } from "./message-action-names.js";

export { CHANNEL_MESSAGE_ACTION_NAMES } from "./message-action-names.js";
export type {
  BaseProbeResult,
  BaseTokenResolution,
  ChannelAccountSnapshot,
  ChannelAccountState,
  ChannelAgentPromptAdapter,
  ChannelAgentTool,
  ChannelAgentToolFactory,
  ChannelCapabilities,
  ChannelCrossContextPresentationFactory,
  ChannelDirectoryEntry,
  ChannelDirectoryEntryKind,
  ChannelExposure,
  ChannelFocusedBindingContext,
  ChannelGroupContext,
  ChannelHeartbeatDeps,
  ChannelId,
  ChannelLegacyStateMigrationPlan,
  ChannelLogSink,
  ChannelMentionAdapter,
  ChannelMessageActionAdapter,
  ChannelMessageActionContext,
  ChannelMessageActionDiscoveryContext,
  ChannelMessagePreparedSendPayloadContext,
  ChannelMessageToolDiscovery,
  ChannelMessageToolSchemaContribution,
  ChannelMessagingAdapter,
  ChannelMeta,
  ChannelOutboundSessionRoute,
  ChannelOutboundTargetMode,
  ChannelPollContext,
  ChannelPollResult,
  ChannelReplyTransport,
  ChannelSecurityContext,
  ChannelSecurityDmPolicy,
  ChannelSetupInput,
  ChannelStatusIssue,
  ChannelStreamingAdapter,
  ChannelStructuredComponents,
  ChannelThreadingAdapter,
  ChannelThreadingContext,
  ChannelThreadingToolContext,
  ChannelToolSend,
  ChannelTtsVoiceDeliveryCapabilities,
  PreferredAudioFileFormat,
} from "./types.core.js";
export type {
  ChannelActionAvailabilityState,
  ChannelAllowlistAdapter,
  ChannelApprovalAdapter,
  ChannelApprovalCapability,
  ChannelApprovalDeliveryAdapter,
  ChannelApprovalForwardTarget,
  ChannelApprovalInitiatingSurfaceState,
  ChannelApprovalKind,
  ChannelApprovalNativeAdapter,
  ChannelApprovalNativeDeliveryCapabilities,
  ChannelApprovalNativeDeliveryPreference,
  ChannelApprovalNativeRequest,
  ChannelApprovalNativeSurface,
  ChannelApprovalNativeTarget,
  ChannelApprovalRenderAdapter,
  ChannelApproveCommandBehavior,
  ChannelAuthAdapter,
  ChannelCapabilitiesDiagnostics,
  ChannelCapabilitiesDisplayLine,
  ChannelCapabilitiesDisplayTone,
  ChannelCommandAdapter,
  ChannelCommandConversationContext,
  ChannelConfigAdapter,
  ChannelConfiguredBindingConversationRef,
  ChannelConfiguredBindingMatch,
  ChannelConfiguredBindingProvider,
  ChannelConversationBindingSupport,
  ChannelDeliveryCapabilities,
  ChannelDirectoryAdapter,
  ChannelDoctorAdapter,
  ChannelDoctorConfigMutation,
  ChannelDoctorEmptyAllowlistAccountContext,
  ChannelDoctorLegacyConfigRule,
  ChannelDoctorSequenceResult,
  ChannelElevatedAdapter,
  ChannelGatewayAdapter,
  ChannelGatewayContext,
  ChannelGroupAdapter,
  ChannelHeartbeatAdapter,
  ChannelLifecycleAdapter,
  ChannelLoginWithQrStartResult,
  ChannelLoginWithQrWaitResult,
  ChannelLogoutContext,
  ChannelLogoutResult,
  ChannelOutboundAdapter,
  ChannelOutboundChunkContext,
  ChannelOutboundContext,
  ChannelOutboundFormattedContext,
  ChannelOutboundPayloadContext,
  ChannelOutboundPayloadHint,
  ChannelOutboundTargetRef,
  ChannelPairingAdapter,
  ChannelResolveKind,
  ChannelResolveResult,
  ChannelResolverAdapter,
  ChannelSecretsAdapter,
  ChannelSecurityAdapter,
  ChannelSetupAdapter,
  ChannelStatusAdapter,
} from "./types.adapters.js";
export type { ChannelMessageCapability } from "./message-capabilities.js";
export type { ChannelPlugin } from "./types.plugin.js";

/** Stable message action name union derived from the registered action list. */
export type ChannelMessageActionName = ChannelMessageActionNameFromList;
